### ISSUE TITLE
expression precedence 順序

### ISSUE THREAD

**Issue by marmot0814** [compiler-f19/Discussion#101]
助教您好,
在hw2的spec裡面有說明expression operator們的順序

>  - #### expressions
> 
>     Arithmetic expressions are written in infix notation, using the following operators with the precedence:
> 
>     ||Operator|
>     |:-:|:-:|
>     |negative|**`-`**|
>     |addition|**`+`**|
>     |subtraction|**`-`**|
>     |multiplication|**`*`**|
>     |division| **`/`**, **`mod`**|
>     |relational| **`<`**, **`<=`**, **`<>`**, **`>=`**, **`>`**, **`=`** |
>     |logical|**`and`**, **`or`**, **`not`**|
而過去有個issue有提問到順序是上面較為優先 (#42)
> 同學您好：
> 
> > 1. expression precedence 順序
> 
> 越上面越優先。

所以請問是先加減後乘除的意思嗎?

**Comment by Naetw** [comment]
同學你好

不好意思，當時助教只看到了 negative，沒注意看 + 居然在上面。大概看了下同學的 yacc rule，看起來不用做修正。基本上還是先乘除後加減。

後來也發現 hw3 也沒測到這件事，只有測了 negative 以及 `()` 的優先順序，為避免有同學完全照著 #42 去實作，hw4, 5 這類狀況都會用 `()` 去處理。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by marmot0814** [comment]
好的 
辛苦你們了~
