### ISSUE TITLE
loop parameters的檢查

### ISSUE THREAD

**Issue by samuelyutt** [compiler-f19/Discussion#103]
根據for的描述
The loop parameters used to compute an iteration count must be in the incremental order and greater than or equal to zero.
請問助教如果當loop parameters是variable reference的狀況下，要怎麼檢查值的大小？
還是說loop parameters只有可能是constants嗎？

**Comment by Naetw** [comment]
> 還是說loop parameters只有可能是constants嗎？

在 hw2 的語法限制就已經只能是 constant 了。
