### ISSUE TITLE
關於#97的scope

### ISSUE THREAD

**Issue by xieft180** [compiler-f19/Discussion#104]
[#97](https://github.com/compiler-f19/Discussion/issues/97) 中提到func的redeclaration：
```
self;
func(): boolean; //func1
    begin
    end
end func


begin  
    var a: array 1 to 10 of array 10 to 100 of integer;
    var func: 100; // func2
    print a[func()][0]; //func3
end
end self
```
助教的回答是func1和func2算作重複宣告。
但func1的scope是0(global)，func2的scope是1(local)，按照Scope Rule

> Name must be unique within a given scope. Within the inner scope, the identifier designates the entity declared in the inner scope; the entity declared in the outer scope is hidden within the inner scope.

func2的宣告在1(local)的scope内，應該覆蓋了func1，

> Unlike the normal variable, the symbol of a loop variable can not be redeclared whether it's in the same scope or the inner scope.

而且只有for loop提到了對内部scope的限制。
因此我感覺應該是，func1的scope是0(global)，func2的scope是1(local)，兩者不算redeclaration。而func3由於處於1(local)，因此func()要報錯。
請助教解答，謝謝！

**Comment by Naetw** [comment]
同學你好

你的理解是正確的。在 #97 助教看太快看到 func 重複宣告就直接以為兩個同名的 function Orz，為避免造成已經實作的同學困擾，這次不會有這樣的測資。感謝同學指出問題。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
