### ISSUE TITLE
error output 順序

### ISSUE THREAD

**Issue by franktseng0718** [compiler-f19/Discussion#105]
一開始我對這作業的理解是，error要用postorder的方式印出來，那不就是所有有關這個node的error應該要在traverse完再印嗎，但這幾天我看了一些issue有點困惑，例如program的name跟檔名不同，或是if或是while的condition expression沒有滿足boolean type，那像這種error到底應該在往下traverse完後印，還是因為它是可以比較早發現，且發現的行數也比較前面所以應該發現的時候就先印?

**Comment by Darklanx** [comment]
推
印的時候需要照行數印還是要完全遵照postorder?

**Comment by Naetw** [comment]
postorder。

Starter code 裡面也有寫到：

```
 /*
     * TODO:
     *     Push a new symbol table if needed.
     *     Insert a symbol into current symbol table if needed.
     *     Visit child nodes
     *     Perform semantic analyses
     *     Pop the symbol table if pushed
     */
```

一定是先 visit 當前節點的 child nodes，跳回來後才來檢查當前節點的語意錯誤。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by franktseng0718** [comment]
所以如果一開始就發現program name和檔名不同，這個error應該是最後印的囉?還有一個問題，若function call node的一個argument的expression發現type的error，那要馬上印還是先把這個error存起來等每個expression都被traverse完再印

**Comment by Naetw** [comment]
> 這個error應該是最後印的囉

對。

> 那要馬上印還是先把這個error存起來等每個expression都被traverse完再印

你發現它錯的時候就是在 semantic check 的時候，而 semantic check 的時候本來就要輸出，所以沒有等不等的問題。

**Comment by franktseng0718** [comment]
有可能阿，若是func(1.5,5+true,68)的function call，但原本的function prototype 是func(int,int,int)，那這樣output順序是1.5的type error先還是5+true的binary operator的error先。

**Comment by Naetw** [comment]
你可能有點誤會，在「發現」5 + true 這個 binary operator 的結果型別有誤的時候已經是在 function call node 的 semantic check，代表 binary operator 早已被 traversed 過了，所以當然沒有等不等的問題。等的問題是建立在你先檢查 binary operator 的結果有沒有符合 function prototype，才去 traverse expressions (child nodes)，但是這個明顯跟我們的規定 (postorder) 不符。
