### ISSUE TITLE
Variable Declaration and Reference of Array Type

### ISSUE THREAD

**Issue by tracyliu1220** [compiler-f19/Discussion#106]
想請教一下關於 Variable Declaration and Reference 的 Error 檢查順序問題

> ### Variable Declaration and Reference
> 
> - If there is an error in the array declaration, further checking is unnecessary when visiting the Variable Reference Node which is a reference to that array.

請問如果有一個 array declaration 既是 redeclare index 也有問題
它要噴 redeclare error 還是 index bound error 呢還是兩個都噴？兩個的話順序是什麼呢？

**Comment by Naetw** [comment]
只要輸出 redeclaration error 就好，發現重複宣告基本上就是讓這個 symbol 消失在 symbol table 中，所以有關這個重複宣告的 symbol 的後續檢查也不需要。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by tracyliu1220** [comment]
啊我還想再問一個

那 refers 到一個 index 有問題 array declaration 的 variable reference

也不能噴 undeclare error 嗎？還有這個 variable reference 的 subscript 也不用檢查？

**Comment by Naetw** [comment]
index 有問題不會消失在 symbol table，只有重複宣告會。再來因為它在宣告就有錯誤發生，所以有關它的後續檢查都不需要。
