### ISSUE TITLE
function name redeclare

### ISSUE THREAD

**Issue by Darklanx** [compiler-f19/Discussion#107]
如果function name redeclare了 body也有錯
請問是哪一個error先噴
按照post order要先噴body
可是body應該會需要看到function name在symbol table裡面

**Comment by Naetw** [comment]
這牽涉到 #98 討論的議題，由於以往 symbol redeclaration 與 semantic definition 分開設計的緣故，目前的版本是 name redeclaration 會先輸出（在過去是會先單獨跑 symbol table 的建立與檢查），與 postorder 的規範有出入。這是把兩份合併的時候沒有考慮周延的結果，所以這次不會有這樣的測資。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
