### ISSUE TITLE
assignment to constant

### ISSUE THREAD

**Issue by Darklanx** [compiler-f19/Discussion#108]
如果assignment右邊expression錯了
左邊是constant
那需要噴左邊是constant的錯ㄇ？
因為左邊是不是constant是assignment要檢查的
可是右邊expression是child
理論上不用噴？

**Comment by Darklanx** [comment]
再追問一個 如果assignment左右都是array 那這樣要噴幾個array assignment is not allowed?
只用噴左邊的？

**Comment by Naetw** [comment]
> 那需要噴左邊是constant的錯ㄇ？

要啊，照著 error-msg.md 所描述的順序，會先檢查左邊，接著檢查右邊發現有霧就可以離開了。

> 再追問一個 如果assignment左右都是array 那這樣要噴幾個array assignment is not allowed?
只用噴左邊的？

左邊的，https://github.com/compiler-f19/Discussion/issues/98#issuecomment-568905579。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by Darklanx** [comment]
可是左邊是constant這件事不是variable reference有錯 是assign statement的錯 那既然右邊expression錯了 他是assign statement的child 我們檢查左邊var ref沒錯 右邊expression有錯 那應該就不會輪到檢查assign statement左邊是不是constant了

**Comment by Naetw** [comment]
當然不是 variable reference 有錯啊，在 error-msg.md 中 assignment node 的檢查你可以注意看，就是先看跟左邊有關的錯誤再看右邊。

**Comment by tracyliu1220** [comment]
我也想補一個問題，想問一下實作的順序

是 traverse variable reference -> check variable reference error -> traverse expression -> check expression error

還是 traverse variable reference -> traverse expression -> check variable reference error -> check expression error

然後中間有錯就停下來（？

**Comment by Joechiaotung** [comment]
`var a:2;`
`a[0] := 1+ 0.2+true;`
想請問助教那如果是上面這種情況會噴什麼錯?

**Comment by Naetw** [comment]
> 我也想補一個問題，想問一下實作的順序

若你是指 assignment 中的 variable reference 跟 expression 的話：

traverse variable reference -> check variable reference error -> traverse expression -> check expression error

每個節點會先跑 visit child nodes，而且跑完 child nodes 會跑完 semantic check 才回去，所以 expression 的 traverse 會在後面。

> 然後中間有錯就停下來（？

停下來指的都是「同一個節點」可能會有多個語意錯誤要檢查，那中間有其中一個有誤就跳開。除了 program node 頭尾都要檢查外。

> 想請問助教那如果是上面這種情況會噴什麼錯?

1. traverse variable reference: over array subscript
2. traverse binary operator: invalid operands to binary operation '+' ('real' and 'boolean')

**Comment by Naetw** [comment]
補充

> 可是左邊是constant這件事不是variable reference有錯 是assign statement的錯 那既然右邊expression錯了 他是assign statement的child 我們檢查左邊var ref沒錯 右邊expression有錯 那應該就不會輪到檢查assign statement左邊是不是constant了

spec 有提到要跟 child node 相關的錯誤才不用檢查，而左邊是不是 constant 的錯誤跟右邊 expression 的錯誤無關，所以要檢查。

**Comment by tracyliu1220** [comment]
不好意思還有個問題QQ

所以針對 variable reference `arr[idx1][idx2]`

一樣也是如果 `idx1` 被檢查出錯了就不 traverse `idx2` 了嗎

先謝謝助教辛苦回答我們了

**Comment by Naetw** [comment]
> 一樣也是如果 idx1 被檢查出錯了就不 traverse idx2 了嗎

是的。這邊跟 function call 的檢查規則有點出入，是設計時沒有考慮周延的結果。相關討論見 #92。

**Comment by phlee1117** [comment]
助教你好，你說
```
var a:2;
a[0] := 1+ 0.2+true;
```
會噴
1. traverse variable reference: over array subscript
2. traverse binary operator: invalid operands to binary operation '+' ('real' and 'boolean')

但Assignment測資裡面第12行
`ff := arr[12];`
其中arr[12]是一個陣列
他只有噴
```
<Error> Found in line 12, column 5: use of undeclared identifier 'ff'
        ff := arr[12];
        ^
```
是因為只要variable reference或expression其中一個有錯，就不用檢查assignment本身的semantic error了嗎？
所以實作順序
traverse variable reference -> check variable reference error -> traverse expression -> check expression error
這四步一定都要完成後，而且variable reference和expression都沒有出現error
才去檢查assignment本身的semantic error？
檢查assginment本身的semantic error時，依照error_msg.md描述的error從上到下，只要有出現任何一個error就跳出檢查？

**Comment by Naetw** [comment]
> 這四步一定都要完成後，而且variable reference和expression都沒有出現error
才去檢查assignment本身的semantic error？
> 檢查assginment本身的semantic error時，依照error_msg.md描述的error從上到下，只要有出現任何一個error就跳出檢查？

助教的實作是有 error 還是會先跑去 assignment 的 semantic check，但是它在檢查相關的錯誤時，會先檢查 child node 有沒有錯誤發生，若有就會跳離。

像是 assignment 本身是先檢查 variable reference 相關的錯誤（constant, loop）所以發現 variable reference 有錯誤，就不檢查了直接跳離。

**Comment by marmot0814** [comment]
助教您好,
我對上面某兩篇問答有點疑問, 問題大概是語意有點模糊導致有兩種解釋意思, 想來確定一下是那一個

問題:
> 不好意思還有個問題QQ
> 
> 所以針對 variable reference `arr[idx1][idx2]`
> 
> 一樣也是如果 `idx1` 被檢查出錯了就不 traverse `idx2` 了嗎
> 
> 先謝謝助教辛苦回答我們了

回答:
> > 一樣也是如果 idx1 被檢查出錯了就不 traverse idx2 了嗎
> 
> 是的。這邊跟 function call 的檢查規則有點出入，是設計時沒有考慮周延的結果。相關討論見 #92。

問題用詞是用"traverse" idx2, 意思是如果idx1回傳的不是int, 我就不跑idx2的semantic check
ex. arr["str"+"str"][1 + true]
上面的例子只會回傳
```
"str"+"str" 不是int 不能放array index
```
但不跑後面的ExpressionNode semantic check

但是在spec中的設計方式是
```
跑完所有的child的semantic check
開始自己的semantic check
一有錯誤就跳開自己回到父節點層
```

這樣在上面的例子
ex. arr["str"+"str"][1+true]
會回傳兩種錯誤
```
"str"+"str"不是int 不能放array index
binary operator + 不能接 int跟boolean
```

**Comment by Naetw** [comment]
第二個是對的沒錯。上面回答是助教沒看仔細，助教那邊回答的原意是你在 variable reference 的檢查時，若發現 idx1 不是 integer，那就不用檢查 idx2 是不是 integer，traverse 這件事在檢查 indices 是不是 integer 之前就會發生沒錯。
