### ISSUE TITLE
Type Coercion and Comparison以及return value的問題。

### ISSUE THREAD

**Issue by baili0411** [compiler-f19/Discussion#109]
助教您好：
在關於function的semantic判斷部分，有這一句話：
The type of the return statement inside the function must be the same as the return type of the function declaration.
而Type Coercion and Comparison下是寫
An integer type can be implicit converted into a real type due to several situations, such as assignments, parameter passing, or arithmetic expressions.
沒講到關於return value的部分，所以return value照這樣我認為應該是不能套用integer implicit convert成real的，但是它字面上寫such as，可能不只這些狀況，所以我想和助教確認一下我理解的對不對。

**Comment by Naetw** [comment]
同學你好

因為沒有明確規範到，同學可以決定要不要套用到 return value，助教的版本目前是有套用的。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
