### ISSUE TITLE
發布作業一

### ISSUE THREAD

**Issue by ianre657** [compiler-f19/Discussion#11]
@compiler-f19/2019-students 
作業一發布拉!!

請到以下網頁點選 hw1 連結來接受作業 :
[private/homework](https://github.com/compiler-f19/Compiler-f19-private/tree/master/Homework)

早早寫作業，早早出去玩 !

**Comment by YSHsieh7777** [comment]
@compiler-f19/2019-students 

作業有問題一樣請至 https://github.com/compiler-f19/Discussion/issues 發 issue 並選擇 hw1 的模板或是寄信到 Compiler-f19@sslab.cs.nctu.edu.tw（請盡量不要使用 e3 寄信），感謝同學的配合。

**Comment by ianre657** [comment]
10/3 11:58  暫時關閉 hw1 邀請碼，大概一小時之後會再開放同學接受作業

**Comment by marmot0814** [comment]
hi,
sample-solution的每個case是不是都少輸出一行 
{行數}: end

**Comment by ianre657** [comment]
@maomao0819 嗨 可不可以直接發一篇 issue 呢

**Comment by ianre657** [comment]
10/3 20:00 暫時關閉 hw1 邀請碼打 patch 給已接受作業的同學。預估半小時後重開

**Comment by ianre657** [comment]
10/10
16:30 分時我會鎖住 hw1 邀請碼半小時來打補丁給各位。預計最多也是半小時後再次重開
