### ISSUE TITLE
Redeclaration 和 program name

### ISSUE THREAD

**Issue by baili0411** [compiler-f19/Discussion#112]
助教您好：
剛剛看到助教對於前面issue function name可以被inner scope的變數名字蓋過的修正了，所以在scope上面只有提到loop_var不能再inner scope重複，所有其他的(包括program name)都可以被蓋過是嗎?

**Comment by Naetw** [comment]
是的。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
