### ISSUE TITLE
Type Coercion of Array

### ISSUE THREAD

**Issue by tracyliu1220** [compiler-f19/Discussion#114]
請問 int [3][3] 可以傳到 func(real [3][3]) 裡面嗎

**Comment by Naetw** [comment]
> 請問 int [3][3] 可以傳到 func(real [3][3]) 裡面嗎

這個同樣沒有很清楚地定義好，助教認為「可以」應該是比較好實做的。
為避免同學需要額外修改，同學可以視自己方便的方式去實作，這次不會有這樣的測資。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
