### ISSUE TITLE
Function call非function symbol的處理

### ISSUE THREAD

**Issue by baili0411** [compiler-f19/Discussion#115]
助教您好：
抱歉那麼晚還有問題，剛剛在做最後check的時候突然想到的，假如function call 的ID對應到的是一個變數的話，那要輸出的是哪種錯誤，是要用function undeclared嗎? 感覺這個比較合理，太多/太少parameter好像怪怪的。

**Comment by Naetw** [comment]
同學你好

> 是要用function undeclared嗎? 

是的。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
