### ISSUE TITLE
Function Call Error

### ISSUE THREAD

**Issue by phlee1117** [compiler-f19/Discussion#116]
請問Function Call的檢查中，是不是要先visit每一個argument之後，才能開始檢查argument數量是否跟symbol table中的(當初declared的)parameter數量相同呢？
例如以下範例
```
func():integer;
begin
end
end func

func(1+"string");
```
得先印出1+"str"的binary operator錯誤，之後才檢查Function Call本身的其他semantic error？

另外，像這種argument本身就有錯的，是不是只要任一個arguemnt有錯，就不用檢查argument總數量（也當然不用檢查type）有沒有對到？

**Comment by Naetw** [comment]
> 請問Function Call的檢查中，是不是要先visit每一個argument之後，才能開始檢查argument數量是否跟symbol table中的(當初declared的)parameter數量相同呢？

對哦。

> 得先印出1+"str"的binary operator錯誤，之後才檢查Function Call本身的其他semantic error？

是的。

> 另外，像這種argument本身就有錯的，是不是只要任一個arguemnt有錯，就不用檢查argument總數量（也當然不用檢查type）有沒有對到？

助教認為數量是否相符跟 function declaration 本身比較有關，所以還是可以檢查。但是跟其他問題一樣，這邊也沒有很明確的規範，為避免其他同學困擾，不會有這樣的測資。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by phlee1117** [comment]
```
func():integer;
begin
end
end func

func(1+"string", 1+"string");
```
就會分別印出兩個binary op的error，最後再說argument數量有誤？

**Comment by iamch15542** [comment]
助教您好，
您之前說過 function call 的param的type是否正確是每個都要檢查並且輸出
單純想問一下，那麼
> func(a, b, c:integer;):integer;
> begin
> end
> end func

如果function call 是長這樣的話
> func(1, 1+true, false)

因為 1 + true 這個binary operator已經錯誤了，所以並不會有type回傳
那麼當我們回到function call node 檢查他的type是否正確的時候，是不是可以直接忽略掉
只輸出後面 false 的type錯誤？

**Comment by Naetw** [comment]
> 就會分別印出兩個binary op的error，最後再說argument數量有誤？

是的沒錯。

> 您之前說過 function call 的param的type是否正確是每個都要檢查並且輸出
> 因為 1 + true 這個binary operator已經錯誤了，所以並不會有type回傳
那麼當我們回到function call node 檢查他的type是否正確的時候，是不是可以直接忽略掉
只輸出後面 false 的type錯誤？

由於這個一開始沒有講清楚，又有不少人有疑問，目前決定「每個都檢查」跟「其中一個參數型別錯誤就跳出」都行（實作上就差 loop 裡面的 `if` 檢查內有沒有加 return 而已，應該不會影響到已經實作的同學太多）。
