### ISSUE TITLE
作業五 demo 時段登記

### ISSUE THREAD

**Issue by YSHsieh7777** [compiler-f19/Discussion#118]
@compiler-f19/2019-students 
各位同學好

經過激烈的投票後
demo 日期已經決定在 **1/16 星期四了**
所以作業五的死線就定在 **1/15 23:59:59**，沒有遲交
如果 1/16 有事不能來的同學請趕快寄信給助教**請假**並註明理由
或者是寄信給助教約**提前 demo**，並且提供助教**多個** demo 時段，讓助教選擇
如果沒有請假又沒來 demo 的同學將只能測 **60 分**的測資喔！！ 

請各位到 [時段登記](https://docs.google.com/spreadsheets/d/1yUcucbnVtYPdz2bmDlm_W2O9B6u_BbPrTDczlXdOWGI/edit?usp=sharing) 登記你的 demo 時段
一個時段可以登記兩個人，一個人 15 分鐘
來了就拿 5 分，投票打卡再加 2 分，有夠賺，好 demo，不來嗎？

![demo](https://user-images.githubusercontent.com/30106883/71572559-affda080-2b1a-11ea-824d-9529389abfad.jpg)
---

作業五相較於前兩次作業真的簡單的多
如果前兩次作業不太理想的同學
請一定要好好把握作業五
盡快開始寫作業

**Comment by YSHsieh7777** [comment]
@compiler-f19/2019-students 

提醒一下各位同學，時段登記只開放到星期一的晚上，
請還沒登記的同學盡快登記，
很抱歉我們不開放線上 demo，
若要請假或提前 demo 的同學請盡快寄信給助教，
大家作業五加油！

**Comment by maomao0819** [comment]
TA不好意思 請問我可以改時段嗎

**Comment by YSHsieh7777** [comment]
@compiler-f19/2019-students 

時段登記以及請假開放到今天下午 3:00，
請需要的人趕快登記或寄信請假

**Comment by HelloKKH** [comment]
QQ不好意思問一下在哪demo

**Comment by Naetw** [comment]
工三 618

**Comment by Naetw** [comment]
@compiler-f19/2019-students 同學嗨嗨，如果有空的同學可以提早來 demo，目前很空，早早來 demo 早早放假，感謝各位同學～
