### ISSUE TITLE
期末考範圍

### ISSUE THREAD

**Issue by samuelyutt** [compiler-f19/Discussion#119]
不好意思可以麻煩助教公告一下最後確定的期末考範圍嗎？謝謝！！😭

**Comment by YSHsieh7777** [comment]
@compiler-f19/2019-students 
我記得上禮拜五老師有說考到哪
但我忘記了 QQ
有沒有人記得可以留言一下的
感謝

**Comment by allen880117** [comment]
我記得是到 L13-Control Flow 
因為 L14 Dataflow 上禮拜沒教完所以不考
