### ISSUE TITLE
testcase 範例輸出

### ISSUE THREAD

**Issue by marmot0814** [compiler-f19/Discussion#12]
hi,
sample-solution的每個case是不是都少輸出一行
{行數}: end

**Comment by Naetw** [comment]
同學你好，

範例解答少輸出最後一行是因為 testcase 的檔案行尾沒有 `\n` 字元，因此 scanner 無法判定一行的結束，也就沒有去做輸出。

這是助教的疏忽，稍後會加上 `\n` 讓範例解答跟作業說明的範例輸出相符。感謝同學的提問。

**Comment by ianre657** [comment]
已經打完 patch，在 10/3 20:30 前接受作業的同學才會收到，之後的同學收的作業會自動更新，不會有影響

總共影響 39人 ，如果有人沒被更新到請再通知我，謝謝

![Screen Shot 2019-10-03 at 8 28 12 PM 1](https://user-images.githubusercontent.com/13212935/66126574-59b4ba80-e61c-11e9-8768-2f4cc0f0a604.png)
