### ISSUE TITLE
Bonus 輸入輸出相關疑問 及 C內建 library 的使用

### ISSUE THREAD

**Issue by marmot0814** [compiler-f19/Discussion#120]
助教您好, 請問一下
1) 用risc-v call C library 的 function 在這份作業是合法的嗎? (ex. malloc, free)
2) spec hw4 提到 print 跟 read 會接 scalar type, 但目前 io.c 內的只能接integer, 請問其他 type 的輸入輸出會出現在測資嗎? 如果會的話 print 輸出格式是甚麼?

謝謝

**Comment by YSHsieh7777** [comment]
> 用risc-v call C library 的 function 在這份作業是合法的嗎? (ex. malloc, free)

不合法，C library 同學只能使用 io 相關操作

> spec hw4 提到 print 跟 read 會接 scalar type, 但目前 io.c 內的只能接integer, 請問其他 type 的輸入輸出會出現在測資嗎? 如果會的話 print 輸出格式是甚麼?

這次作業要求只有 integer type，其他 type 放在 bonus 的部份，輸入輸出一律都是單一值接換行，例如：

```c
printf("%d\n", integer);
printf("%f\n", real);
printf("%s\n", string);
```
---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by marmot0814** [comment]
想請問一下
boolean type的輸出格式
感謝

**Comment by YSHsieh7777** [comment]
同學好

沒有輸入輸出，
只會用在程式中的判斷句
