### ISSUE TITLE
stack 大小問題

### ISSUE THREAD

**Issue by yenjushan** [compiler-f19/Discussion#122]
助教您好:
想請問上課說的 stack 大小用 64byte 就夠了的這件事情。
請問 compound statement 包 compound statement 時我們需要為內層新建立一個 stack 嗎?
要是不建立 stack 變數會不會多到 stack 存不下。for 迴圈呢?

**Comment by YSHsieh7777** [comment]
同學好

compound statement 裡面再出現其他 compound statement 的情況不需要再建立一個新的 stack，
for 迴圈裡的 compound statement 也是一樣，
測資裡保證不會有變數多到 stack 放不下的狀況。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by yenjushan** [comment]
想再請問 stack 的大小問題。
spec 中有提到，function 的參數可能多於八個，這樣我們在 function call 時，，必須用到 stack 的空間。
我可以直接把所有參數 push 進 stack 嗎( stack 夠大嗎 )?
還是說我們必須依照 calling convention ，將參數存入a0-a7，多的參數再使用stack的空間。

**Comment by YSHsieh7777** [comment]
同學好

助教希望同學依照 calling convention，先將參數放入 register，不夠的再放進 stack 裡，
但是直接存進 stack 也是可以的，參數的數量加上變數數量不會多到 stack 放不下。
請記得使用到 `print` 和 `read` 這兩個 function 時一定要遵守 calling convention。
