### ISSUE TITLE
function call argument push到stack上問題

### ISSUE THREAD

**Issue by baili0411** [compiler-f19/Discussion#123]
助教您好：
spec中有提到超過8個function參數，就要用其他空間放，因為在calling convention中也沒有提到這部分，雖然說是存在stack上，但是沒有提到說要放stack是要放caller的stack上，之後callee再去抓，或是直接放在callee的stack上，我想請問的是要放誰的stack上，不然我怕對於保證stack放得下這點有影響。

**Comment by YSHsieh7777** [comment]
同學好

放在 caller 的 stack 上。
助教建議同學遇到這類問題可以用 `gcc` 去 dump 出 `RISC-V` 的 assembly 看看一般 compiler 是怎麼處理的。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
