### ISSUE TITLE
compiler.exe產生問題

### ISSUE THREAD

**Issue by dd51108lai** [compiler-f19/Discussion#125]
助教好
在spec中提到要產生一個compiler.exe
但是我非常不懂對於makefile的修改
請問是把parser的名字改掉就好還是還要加一些新指令阿

**Comment by YSHsieh7777** [comment]
同學好

同學把 `Makefile` 裡的 

```
EXEC = $(PARSER)
```

改成

```
EXEC = compiler
```

即可

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
