### ISSUE TITLE
./compiler test.p --output_code_dir [output directory name]的問題

### ISSUE THREAD

**Issue by xx123543** [compiler-f19/Discussion#126]
我輸入這個指令之後只有把riscv-code印出來，資料夾裡並沒有東西，請問一下是有什麼地方要改嗎?

**Comment by YSHsieh7777** [comment]
同學好

這裡要請同學自己在程式裡 parse 這段指令，
並且根據 [output directory name] 來決定輸出的 risc-v assembly 要存到哪個資料夾，
例如若指令為
```
./compiler test.p --output_code_dir risc-v-assembly
```
輸出的 risc-v assembly 就要存到 `risc-v-assembly` 這個資料夾

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by nax1016cs** [comment]
請問助教如果沒有一個路徑符合 [output directory name] 的話，會segmentation fault是正常的嗎，還是自己建資料夾?

**Comment by YSHsieh7777** [comment]
同學好

請同學在程式內判斷資料夾是否存在，
若不存在則建立

**Comment by tracyliu1220** [comment]
請問如果指定A/B/C/.../Z資料夾
就要檢查26個資料夾一路建過去嗎

**Comment by YSHsieh7777** [comment]
> 就要檢查26個資料夾一路建過去嗎

是的

**Comment by marmot0814** [comment]
那路徑會有 .. 嗎
ex. ../test/some.s

那如果有A/B/../C 要確定B有沒有存在嗎

**Comment by YSHsieh7777** [comment]
> 那路徑會有 .. 嗎

不會

**Comment by tracyliu1220** [comment]
請問會有絕對路徑嗎？
會不會遇到沒有權限檢查或創資料夾的路徑呢

還有那個像這樣 spec 等級的更改是不是發個 anouncement 比較好
不然沒有挖到這篇 issue comments 的同學有點可憐 QQ
（spec 中沒有提到要檢查資料夾）

**Comment by YSHsieh7777** [comment]
同學好

 > 請問會有絕對路徑嗎？

不會

 > 會不會遇到沒有權限檢查或創資料夾的路徑呢

不會

 > 還有那個像這樣 spec 等級的更改是不是發個 anouncement 比較好

跟同學說個抱歉，這裡做個修改，助教在測試之前都會先建立資料夾，同學可自行決定要不要建立資料夾，但是還是希望同學可以做個建立資料夾，或是檢查資料夾是否存在的功能，可以讓整個 compiler 的功能更為完整

**Comment by YSHsieh7777** [comment]
@compiler-f19/2019-students 

之前沒看到的同學注意一下，
同學不需要自己創建輸出的資料夾，
助教在測試時會先建好，
同學只要把輸出的檔案存到該資料夾下即可，
但是助教還是建議同學自己寫一個創建資料夾的功能，
或是檢查資料夾是否存在的功能，
可使你的 compiler 功能更為完整
