### ISSUE TITLE
riscv64-unknown-elf-gcc的語法

### ISSUE THREAD

**Issue by ysl19971124** [compiler-f19/Discussion#127]
就我的理解，
我們必須輸出[generated RISC-V assembly file]
riscv64-unknown-elf-gcc [generated RISC-V assembly file] io.c -o [output ELF file] 
再接spike pk [ELF file]
來得到我們所需要的ELF file

所以我打了每個p檔相對應的C file，得到output assembly file
riscv64-unknown-elf-gcc -c -S [input C file] -o [output assembly file]
但是我將output assembly file丟進riscv64-unknown-elf-gcc -o [output ELF file] [input RISC-V instruction file]
卻會出現
/opt/risc-v/bin/../lib/gcc/riscv64-unknown-elf/9.2.0/../../../../riscv64-unknown-elf/bin/ld:condition: file format not recognized; treating as linker script
/opt/risc-v/bin/../lib/gcc/riscv64-unknown-elf/9.2.0/../../../../riscv64-unknown-elf/bin/ld:condition:1: syntax error
collect2: error: ld returned 1 exit status
請問該如何解決　感謝助教

**Comment by YSHsieh7777** [comment]
同學好

```
riscv64-unknown-elf-gcc [generated RISC-V assembly file] io.c -o [output ELF file]
```
這個指令是用來產生 `ELF` file，而
```
spike pk [ELF file]
```
這個指令是在 `spike` 這個 simulator 上執行產生的 `ELF` file

---

請同學在 `[output assembly file]` 的檔名的最後都加上 `.s`作為結尾，
應該可以解決同學的問題

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
