### ISSUE TITLE
如何dump 出 RISC-V 的 assembly?

### ISSUE THREAD

**Issue by dd51108lai** [compiler-f19/Discussion#128]
助教好
在 #123 中有提到
>用 gcc 去 dump 出 RISC-V 的 assembly 看看一般 compiler 是怎麼處理的。

但是用
>riscv64-unknown-elf-gcc -o [output ELF file] [input RISC-V instruction file]

這個指令產生的code似乎不能直接丟parser去dump
可以教學一下該怎麼做嗎

**Comment by YSHsieh7777** [comment]
同學好

請同學寫一個相對應的 `C` code，並用
```
riscv64-unknown-elf-gcc -c -S [input C file] -o [output assembly file]
```
去 dump 出 `risc-v` assembly

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by dd51108lai** [comment]
想再請問一下
有加分題的範例嗎
像是uninitialize string之類的
因為dump出來的code跟spec上的非常不一樣
像是uninitialize的integer他是放在.text並且用.comm
我擔心無法用來參考

**Comment by YSHsieh7777** [comment]
同學好

助教不會提供加分題的範例，
Dump 出來的 assembly 可能跟助教提供的不一樣，
但是兩者都是可行的實作方法，
像是 .comm 其實就是把 object emit 到 .bss segment，
同學可參考 [Manual](https://github.com/riscv/riscv-asm-manual/blob/master/riscv-asm.md) 中的 pseudo operation
