### ISSUE TITLE
Some Ambiguities 

### ISSUE THREAD

**Issue by Darklanx** [compiler-f19/Discussion#13]
## 前綴正號
+3 = 3 嗎？ (ex: var a = 0 + +3)
## 運算式還是雙數字
0 -3 = 0 - 3 or 0, -3 (P語言有負數嗎？)
## Octal floating point?
003.1 是 00, 3.1 還是003.1 (floating point有octal form嗎), 還是不合法？ redundant zero的定義有點模糊

**Comment by Naetw** [comment]
同學好

> +3 = 3 嗎？ (ex: var a = 0 + +3)

這個問題其實不在這次作業的範疇，這次作業做的事情是切 tokens 也就是語彙分析，這種 +3 是否相等於 3 的問題是在語意分析才會做的。不過以目前作業 2 的規格來說 +3（正 3）這種是不合法的語法，所以基本上也跑不到語意分析的階段。

> 0 -3 = 0 - 3 or 0, -3 (P語言有負數嗎？)

同上，這個問題也不在這次範疇。

有，但負數的處理是在「語法」分析，也就是作業 2 才會需要處理。

> 003.1 是 00, 3.1 還是003.1 (floating point有octal form嗎), 還是不合法？ redundant zero的定義有點模糊

是 00 (octal), 3.1 (float)，請見 Float-Point Constants 的章節，有範例是這個狀況的。

沒有 octal form，浮點數的 `.` 前面只能有 decimal integer 跟科學記號的 b 限制相同。這是助教們的疏忽，預計放假前會打 patch，不好意思。

Redundant zero 就是不能有不必要的 0，舉例來說 3.100000 「不會」被解析成一個浮點數，然後它的值是 3.100000，因為在 1 後面的 00000 沒辦法幫浮點數增加意義。

---

@compiler-f19/2019-students 

請注意：Float-point 的 `.` 前面只能有 decimal integer。預計放假前會打 patch 給各位，造成困擾不好意思。

**Comment by Naetw** [comment]
@compiler-f19/2019-students 

同學請注意，上面提到 003.1 說會被切成 00 (octal), 3.1 (float) 是「**錯誤**」的，助教把它跟作業說明中的 009.1 當作同一個狀況了。正確情況是，因為 3 還在 octal 的範圍內，所以應該要被 octal 給吃進去，所以正確的分析結果是：

```
<oct_integer: 003>
Error at line x: bad character "."
```

造成誤會非常抱歉。

TA
