### ISSUE TITLE
如何debug生出來的.s檔

### ISSUE THREAD

**Issue by TOMxLEON** [compiler-f19/Discussion#130]
請問要如何知道我寫出來的.s檔是哪邊出錯？或是說有沒有其他測資的.s檔的範例解答？
舉個例子，我照著spec的步驟寫出一個架構之後，在跑test的的variableConstant生出的.s檔長這樣
.file "variableConstant.p"
.option nopic
.bss
gv:
.word 0
.text
gc:
.word 2
.text
.align 2
.global main
.type main, @function
main:
addi sp, sp, -64
sd ra, 56(sp)
sd s0, 48(sp)
addi s0, sp, 64
.text
lc:
.word 4
li t0, 1
la t1, gv
sw t0, 0(t1)
li t0, 3
sw t0, -20(s0)
la t0, gv
lw a0, 0(t0)
jal ra, print
la t0, gc
lw a0, 0(t0)
jal ra, print
lw a0, -20(s0)
jal ra, print
la t0, lc
lw a0, 0(t0)
jal ra, print
ld ra, 56(sp)
ld s0, 48(sp)
addi sp, sp, 64
jr ra
.size main, .-main
執行後看起來它是壞掉了，像這樣
bbl loader
z  0000000000000000 ra 0000000000010106 sp 000000007f7e9b00 gp 0000000000025040
tp 0000000000000000 t0 00000000000100e2 t1 000000000000000f t2 0000000000000000
s0 000000007f7e9b40 s1 0000000000000000 a0 0000000000000001 a1 000000007f7e9b48
a2 0000000000000000 a3 0000000000000010 a4 0000000000000001 a5 0000000000000000
a6 000000000000001f a7 0000000000000000 s2 0000000000000000 s3 0000000000000000
s4 0000000000000000 s5 0000000000000000 s6 0000000000000000 s7 0000000000000000
s8 0000000000000000 s9 0000000000000000 sA 0000000000000000 sB 0000000000000000
t3 0000000000000000 t4 0000000000000000 t5 0000000000000000 t6 0000000000000000
pc 000000000001016c va 0000000000000004 insn       00000004 sr 8000000200046020
An illegal instruction was executed!
要怎麼知道那個illegal instruction是什麼？謝謝。

**Comment by YSHsieh7777** [comment]
同學好

不好意思助教目前並沒有找到一個比較好的 debug 方法，
最快的方法可能還是自己了解 instruction 後去找到程式中問題，
另外可以確定的是 `qemu` + `gdb` 是可行的 debug 方法，
只是這部份可能要請同學自己去研究，
如果有其他同學找到比較好的 debug 方法也歡迎補充，謝謝
