### ISSUE TITLE
有關 Floating Point / Boolean / io.c 的疑問

### ISSUE THREAD

**Issue by allen880117** [compiler-f19/Discussion#134]
助教您好
請問一下
Floating Point 和 Boolean 的Bonus 具體而言要做到什麼程度
* 假如說我沒有做Bonus中的Array 那 Boolean 和 Floating Point 還需要支援 Array 的操作嗎?
* 另外 Print / Read 需要支援 Boolean 還有 Floating Point 嗎 ?

還有 io.c 是助教會在DEMO時幫我們Link
還是我們需要自己在生產出Code，還沒Link前就要將其放入Code中做為一部份?

**Comment by YSHsieh7777** [comment]
> 假如說我沒有做Bonus中的Array 那 Boolean 和 Floating Point 還需要支援 Array 的操作嗎?

不需要，即使你有做 Array 的加分題也不需要，Floating Point 的要求和 spec 中 Integer 一樣

> 另外 Print / Read 需要支援 Boolean 還有 Floating Point 嗎 ?

Boolean 不需要，但是 Floating Point 需要

> 還有 io.c 是助教會在DEMO時幫我們Link
> 還是我們需要自己在生產出Code，還沒Link前就要將其放入Code中做為一部份?

助教在 Demo 時會幫你們 link，但是有做加分題的同學請自己準備自己的 `io.c`，function 的名稱和輸入參數由同學自己決定，測資中的 `print` 和 `read` 一律都只會接單一值
