### ISSUE TITLE
if while相關問題

### ISSUE THREAD

**Issue by zzycc** [compiler-f19/Discussion#135]
請問
condition 裡面的expression裡面會有 and 或 or的運算子嗎?

**Comment by YSHsieh7777** [comment]
@compiler-f19/2019-students 

同學注意一下，基本測資中不會有 `and` `or` `not` 運算子，同學可以自行決定是否實做，
但是 `Boolean Type` 的加分題中的測資就會出現上述計算子

**Comment by zzycc** [comment]
所以是指
如果沒有做boolean type就不會需要處理and or not
隱藏測資也不會有
是這樣的意思嗎

**Comment by Naetw** [comment]
對的
