### ISSUE TITLE
Function 名稱 和 Label 名稱 是否會衝突

### ISSUE THREAD

**Issue by allen880117** [compiler-f19/Discussion#136]
助教您好
 
我目前是參考範例
產生code中的label都是以 `L0` `L1` `L2` 等 `L` 後面接數字的形式產生 

但若是出現Function 名稱和這些 Label 相同的情況下，就會產生重複使用的問題。
我們需要去考慮這種情況嗎?

**Comment by YSHsieh7777** [comment]
同學好

同學不需要考慮這種情況。
