### ISSUE TITLE
Demo修正

### ISSUE THREAD

**Issue by dd51108lai** [compiler-f19/Discussion#138]
助教好
我早上demo的時候因為路徑問題而被扣分
但是現在我想到了可能的問題
想請問可以約下午或晚上去補救嗎

**Comment by YSHsieh7777** [comment]
同學好

剛剛 demo 時已經幫你修正並重測了，
然後路徑問題後來決定扣 10%，
不能補救

**Comment by dd51108lai** [comment]
我想應該把相對改成絕對路徑就好了說...
