### ISSUE TITLE
幾個小問題

### ISSUE THREAD

**Issue by YongFan** [compiler-f19/Discussion#14]
助教你好
### 1. 測資中的 oct 和 float
如果改成 012123127.112321
若沒有 lookahead 的額外細處理 **012123127** 會先被當作 **octal**
然後 **stderr bad character "."**

助教這邊是因爲要求 float 沒有 redundant zero
我目前是單純簡單設計 RE ` 0|{Digits}... `
- 是否還需要額外處理這種case?
- 以及token切出來是如何?

我也蠻好奇 下面這個情況，寓意會怎麽分析?
```
var a := 
<oct: 00> 
<float:9.1>
```

### ~~2. comment 的 /\* 與 \*/~~
~~假設我input case為~~
```
/* abc

     */ a;
```
~~對比測資要求，我覺得正確答案應該是~~
```
1: /* abc
2:
<KWvar>
<id: a>
3:     */ var a
```
這一塊我打著 issues 時不小心地解決掉了，上述解法沒錯吧

### 3. error handle
missing quotes 的部分需要怎麽handle嗎
如 input 有
![image](https://user-images.githubusercontent.com/22821761/66307401-f33edd80-e936-11e9-88fb-680793aa9ee2.png)
普通這樣handle也可以吧? 
![image](https://user-images.githubusercontent.com/22821761/66307736-c8a15480-e937-11e9-9b63-0e7c70a796f1.png)

### 4. 這行有誤，測資要求的是大寫的 "E"rror
![image](https://user-images.githubusercontent.com/22821761/66307892-3fd6e880-e938-11e9-98f8-c5e13bf2048b.png)

---
雖然做完通過了，但是感覺還是漏掉了什麽
從題目來看起來有隱藏測資，所以感覺事情沒那麽簡單
![image](https://user-images.githubusercontent.com/22821761/66308782-77469480-e93a-11e9-8b54-a6e39f5a0ae5.png)

**Comment by Naetw** [comment]
同學你好

> 1. 測資中的 oct 和 float

不需要額外處理，讓 lex 照著 spec 設計的 octal 與 float 去切就好。

切出來就如你所說的，012123127 會被視作 octal，而直接遇到 `.` 會是個 bad character，因為 spec 中描述的語彙定義沒有以 `.` 做開頭的。所以分析到這就發生 error 而停止是正常的。

> 2. comment 的 /* 與 */

你的 input case 跟 output 不太相符，我以 output 裡的 source 來回答，你的結果沒有錯。

> 3. error handle

不行。因為是 bad character，只需要印出第一個不合的字元即可，所以錯誤訊息應該是：

```
Error at line 3: bad character """
```

所有錯誤請以 spec 中 error handling 章節的格式去輸出即可，不需要自己幫錯誤訊息加上其他描述。

> 4. 這行有誤，測資要求的是大寫的 "E"rror

是的，"error" 應該要改成 "Error"。
這是助教的疏忽，因為今年重新實做作業的解答，並修改了一些 spec，導致有些部分沒有修改乾淨，造成困擾非常抱歉。這部分的 patch （修改 spec 描述）同樣會在週三一起打 patch 給同學。

---

若上述回答有解決同學疑問，請關閉這個 issue；若沒有，可在下方繼續討論，感謝同學配合。

TA
