### ISSUE TITLE
想請教OCT的判讀邏輯

### ISSUE THREAD

**Issue by imgradually** [compiler-f19/Discussion#15]
在case1的測資中有一個009.1
範例解答的切法是
<oct_integer: 00>
<float: 9.1>
又在case5的測資中有一個00123E4
範例解答的切法是
<oct_integer: 00123>
<id: E4>

然而在前面有同學問到關於012123127.112321的OCT判斷
助教的回答是"012123127 會被視作 octal，而直接遇到 . 會是個 bad character"
是否與case1和case5的解答相矛盾？
因為
1. 從case5可得知OCT可以接受00後有數字
2. 在case1沒有讀00後的數字，讓我認為是因為後面有小數點的緣故
從以上的觀點我以為這句話的判斷應該被切為
<oct_integer: 01212312>
<float: 7.112321>

這部分我有點理解障礙
麻煩助教解釋判斷邏輯

**Comment by Naetw** [comment]
同學你好

> 是否與case1和case5的解答相矛盾？

沒有，因為 octal 是八進位，所以它只吃 0-7 的數字，9 超過了它能處理的範圍，所以會被留下來放到下一次 rule matching 中。

---

若以上回答有解決同學的疑惑，請把這個 issue 關掉；若還有其他問題，可在下面提出，感謝同學配合。

TA
