### ISSUE TITLE
Quotation mark in string

### ISSUE THREAD

**Issue by javiersim** [compiler-f19/Discussion#16]
To represent a quotation mark in a string it needs two quotation mark consecutively but when it is matched by the grammer both quotation mark will be included into yytext and we are cannot remove a character in yytext so are we going to need another char array to temporary store yytext and modified it afterwards?

**Comment by Naetw** [comment]
How you implement will not affect your grade, as long as the result is matched with the specification. By the way, manipulating the contents of yytext is possible and allowed.

---

If reply above has solved your problem, please close this issue. If you have further question, please reply in this thread. Thanks for your cooperation.

TA
