### ISSUE TITLE
floating point / signed symbol / github push problem

### ISSUE THREAD

**Issue by nax1016cs** [compiler-f19/Discussion#17]
助教好，有幾個問題想請教。

1. 助教在同學的回答當中有提到，3.100000不會被解析成浮點數 ，這樣的話要如何表達?

2. 想確認一下在這次的作業中，在integer、floating point 、scientific notation 是否不用處理正負號，只需要切成 '+' '- 和相對應的數字'即可。

3. 作業要push到master，還是加patch的那個branch?

**Comment by Naetw** [comment]
同學你好

> 1. 助教在同學的回答當中有提到，3.100000不會被解析成浮點數 ，這樣的話要如何表達?

助教的意思是，它不會被解析成 <float: 3.100000>。3.100000 會被解析成一個浮點數 <float: 3.1> 而剩下的 0 會再交由其他的語彙規則去解析。

> 2. 想確認一下在這次的作業中，在integer、floating point 、scientific notation 是否不用處理正負號，只需要切成 '+' '- 和相對應的數字'即可。

是。

> 3. 作業要push到master，還是加patch的那個branch?

請 push 到 master。patch 的部分請視情況自行決定要不要 merge，助教建議是要，才能練習並比較清楚協作時常需要做的 merge 是怎麼一回事。

---

若以上回答有解決同學的疑惑，就麻煩把這個 issue 關掉；若還有其他問題，可在下面提出，感謝同學配合。

TA
