### ISSUE TITLE
String Format/ Escape Character

### ISSUE THREAD

**Issue by allen880117** [compiler-f19/Discussion#18]
助教您好

1. 請問一下所謂的Embedded newlines是指以輸入文本形似以下狀態嗎?
```cpp=
"abcd
     efgh"
```
2. 請問一下我們輸出的訊息中需要處理跳脫字元嗎，如
```cpp=
INPUT______:  "\tabcd"
SCANNER_MSG:  <string: <tab>abcd> // 請把<tab>當成多個空白
```

謝謝

**Comment by YSHsieh7777** [comment]
同學你好

> 1. 請問一下所謂的Embedded newlines是指以輸入文本形似以下狀態嗎?

是

 > 2. 請問一下我們輸出的訊息中需要處理跳脫字元嗎

除了雙引號需要特別處理之外，同學只需要將string規則match到的ASCII字元原封不動的輸出即可

```
INPUT______:  "\tabcd"
SCANNER_MSG:  <string: \tabcd>
```

---

若以上回答有解決同學的疑惑，就麻煩把這個 issue 關掉；若還有其他問題，可在下面提出，感謝同學配合。

TA
