### ISSUE TITLE
關於原本給的程式的問題

### ISSUE THREAD

**Issue by oilover8728** [compiler-f19/Discussion#20]
1.想問助教 我在還沒改過程式碼前讓他直接跑他印出這樣是正常的嗎
   就是error -> "rror 然後也看不出是哪個字元錯
![1](https://user-images.githubusercontent.com/55472652/66667869-96b92680-ec86-11e9-8362-f338ab04b0ad.PNG)
然後這是example.txt
![2](https://user-images.githubusercontent.com/55472652/66667875-9a4cad80-ec86-11e9-8877-2bd1adceda13.PNG)

2. 然後想請問我修改檔案的時候用editdiff的指令 改完之後:wq後都會多跑出一個.orig的檔案
是正常的嗎 如果不是我要怎麼做才不會讓他多生成這個檔案呢

謝謝助教

**Comment by Naetw** [comment]
同學你好

> 1 想問助教 我在還沒改過程式碼前讓他直接跑他印出這樣是正常的嗎

不正常，助教拿了同學收到作業的初始版本以及你的作業 repo 的版本跑出來結果兩者相同，且跟你提供的結果不同。以下是助教跑出來的結果：

```
<(>
1: (

<(>
2: (

3:

```

助教推測你的 example.txt 除了目前截圖肉眼可見的 `(` 字元外還有其他奇怪的字元，或是實際上你的 `lex.l` 已經有更動過。若需要進一步幫忙，有兩件事可以做：

- 執行指令 `hexdump -C example.txt` 並把輸出結果貼上來
- 請把你工作環境中的 repo 內容 push 到 GitHub repo 好讓助教使用與你相同的版本

> 2. 然後想請問我修改檔案的時候用editdiff的指令 改完之後:wq後都會多跑出一個.orig的檔案
是正常的嗎 如果不是我要怎麼做才不會讓他多生成這個檔案呢

正常的。不過助教以前也沒用過這個指令，相關的操作可以 Google 看看。

---

若以上回答有解決同學的疑惑，請把這個 issue 關掉；若還有其他問題，可在下面提出，感謝同學配合。

TA
