### ISSUE TITLE
關於 Comments 的問題

### ISSUE THREAD

**Issue by samartfang** [compiler-f19/Discussion#23]
1.在/* */ 識別模式下，正則表達式可以識別，但是如何讓輸出能夠顯示行號呢？我的輸出只會把所有都輸出，不輸出行號。

**Comment by Naetw** [comment]
同學你好

> 1.在/* */ 識別模式下，正則表達式可以識別，但是如何讓輸出能夠顯示行號呢？我的輸出只會把所有都輸出，不輸出行號。

這個問題就是同學要自己去想辦法實做的，建議可以參考一下老師 [Lec4](https://github.com/compiler-f19/Compiler-f19-private/blob/master/LectureNotes/L4-Lex.pdf) 的講義，裡面有介紹 `lex` 的相關功能，其中有個功能可以幫助你做出你想要的結果。

---

若以上回答有解決同學的疑惑，請把這個 issue 關掉；若還有其他問題，可在下面提出，感謝同學配合。

TA
