### ISSUE TITLE
Scientific notation 輸出格式

### ISSUE THREAD

**Issue by zzycc** [compiler-f19/Discussion#24]
如果輸入為
123.0E123
請問輸出要是
<scientific: 123E123>
 還是
<scientific: 123.0E123>
或是
<float: 123.0>
<id: E123>

**Comment by Naetw** [comment]
同學你好

作業說明上關於 scientific notations 的描述：`aEb` 中的 `a` 可以是浮點數，所以整串應該要被當成完整的 scientific notation。至於輸出形式請維持原樣，不需要特別去做其他處理。若同學有特別做處理，助教這邊的批改會較為麻煩。

---

若以上回答有解決同學的疑惑，請把這個 issue 關掉；若還有其他問題，可在下面提出，感謝同學配合。

TA

**Comment by zzycc** [comment]
那請問 scientific notation
aEb
a跟b 都需要處理redundant zero的問題嗎
像12.00E0024
改成
12.0E24 輸出

**Comment by Naetw** [comment]
同學你好

作業說明中的 redundant zero 指的是「不要讓多餘的零可以被你設計的浮點數規則給符合」，不是指你輸出的格式。所以如上面回覆說的，可以的話就不要額外處理，保留原樣輸出即可。

---

若以上回答有解決同學的疑惑，請把這個 issue 關掉；若還有其他問題，可在下面提出，感謝同學配合。

TA
