### ISSUE TITLE
繳交 report

### ISSUE THREAD

**Issue by oilover8728** [compiler-f19/Discussion#25]
助教請問我這樣是哪裡有錯嗎
或是應該怎麼做

順便問最後是交lex.l和report這樣嗎
謝謝
![ask](https://user-images.githubusercontent.com/55472652/66860138-27fa0700-efbf-11e9-9302-a20c69b0faac.PNG)

**Comment by ianre657** [comment]
同學你好，報告只要編輯 report/readme.md 的內容就好了，不用產生 pdf 檔案

**Comment by ianre657** [comment]
同學你好，這裡先針對你的命令列上得操作做些說明。

1. 專案資料夾下沒有 `Makefile` 所以我也不知道你這行的意思
2. 報告的話，你只要編輯 `report/README.md` 就可以了，裡面採用 Markdown 語法，還請自己熟悉。
3.  `docs/` 資料夾下方的 `Makefile`，是讓同學產生這次作業規格書的 pdf 檔案用的。跟報告繳交沒關係。不過順道一提，如果你真的想產生規格書檔案，請直接在自己的平台上安裝 `pandoc` 跟`wkhtmltopdf `。`brew` 是一支套件管理程式，要自己安裝，但是大多是 mac 使用者在用。

同學這次作業實際上不需要到 e3 上繳交任何東西，只需要確保在死線時專案下 `src/lex.l`, `report/README.md` 這兩個檔案的內容是最新版本的就好。 我們會自己把同學的專案拉下來針對這兩個檔案做批改。

稍微提醒下時間問題，我們這次會透過 Github API 獲取各位同學的 push 時間作為繳交時間判定，不要午夜過了才執行 `git push`。

如果有問題，還請直接在下方回覆，謝謝
