### ISSUE TITLE
關於pseudocomment的問題

### ISSUE THREAD

**Issue by baili0411** [compiler-f19/Discussion#26]
關於pseudocomment，在說明中提到說要完全match才對option有效果，那請問如果是像
//&S+  \t\n這種有行尾空白或tab字元的狀況psuedocomment有效果嗎?

**Comment by Naetw** [comment]
同學你好

> 關於pseudocomment，在說明中提到說要完全match才對option有效果，那請問如果是像 //&S+ \t\n這種有行尾空白或tab字元的狀況psuedocomment有效果嗎?

有。
請看作業說明的第三個例子：在分析到符合 pseudocomment 的格式後，後面會被視作一般註解而直接忽視。說明中的完整指的是像 `//&S+` 這樣子正常的 pattern 內不能穿插其他的字元，必須完整且連續的吻合 pseudocomment 的 pattern，而吻合後，後面放什麼都沒關係。

---

若以上回答有解決同學的疑惑，請把這個 issue 關掉；若還有其他問題，可在下面提出，感謝同學配合。

TA
