### ISSUE TITLE
.gitignore has no newline at the end

### ISSUE THREAD

**Issue by allen880117** [compiler-f19/Discussion#27]
* `Merge` `Patch 2` 之後，因為每次`Push`都還是會看到`src/scanner`出現。
* 所以我`cat .gitignore` 發現`scanner`那一行好像最後少了newline。
* 所以`git`沒辦法判定`scanner`需要忽略。

**Comment by ianre657** [comment]
我也有發現怎麼有些同學的 scanner 都放上來了，但也沒有花時間去看發生什麼事情，
這是我在編輯 `.gitignore` 疏忽了。

不過考慮到今天晚上就是死線，也不會影響到同學的成績，所以就暫時不打 patch。
感謝 !
