### ISSUE TITLE
Pseudocomments followed by Pseudocomments

### ISSUE THREAD

**Issue by allen880117** [compiler-f19/Discussion#30]
假設今天一個Pseudocomments後面直接緊跟著另一個Pseudocomments的Pattern
```cpp=
//&S-//&T-   <\n>
abc
```
那應該是要

  1. 一個完整的C++-Style Comment是包含newline所以`//&T-`不會發生效果
```cpp=
<id: abc>
(Nothing here since //&S-)
``` 
  2. 完整的`Pattern`有對到，所以`//&T-` 發生效果
   ```cpp=
   (Nothing here since //&T-)
   (Nothing here since //&S-)
   ```

**Comment by Naetw** [comment]
同學你好

一樣請看作業說明中 pseudocomments 的章節，第 3 個例子符合同學考慮的情況：

> `//&S+&S-` This leaves the S option on because the rest of the comment is ignored

請忽略同一行內完整的 pattern 後的所有東西。

---
若以上回答有解決同學的疑惑，請把這個 issue 關掉；若還有其他問題，可在下面提出，感謝同學配合。

TA
