### ISSUE TITLE
作業一截止 / 小小提問

### ISSUE THREAD

**Issue by ianre657** [compiler-f19/Discussion#31]
@compiler-f19/2019-students 

各位同學安安！

作業一的繳交期限在 10/16 23:59:59 已經截止 #11 

雖然前幾次作業跟網站都有公告過繳交事項的說明，但還請容許我在這裏多嘴，在這時間點後的繳交都會被計算成遲交，遲交的分數計算規則就跟作業中的說明相同。

在這個時限之後對 hw1 master branch 有任何 push 行為都會刷新你的繳交時間，所以如果已經完成作業的同學，在兩個星期內請不要對 master branch 有動作，因為我們會持續記錄兩個星期左右。

好的，進入正題。

## HW1 Feedback

想請問各位同學，在做完作業一之後對這次作業的流程 / 體驗 有什麼想法嗎？
比如說 :

+ 在作業的取得 / 流程上有什麼不順暢的地方
+ 作業的規格 / 說明有什麼可以改進的地方
+ 在問問題 / 搜尋問題 上面有什麼不方便或特別欣賞的地方

針對這些內容（或是其他你自己的觀察），你有沒有什麼可以針對此做改進的方法？

希望有想法的同學，可以在下方留言供助教們作為往後作業的參考。如果不方便的公開回應的話也可以寄信給助教團，並在標題中標注 [作業一回饋] 。

謝拉!

**Comment by ysl19971124** [comment]
助教 因為我沒有使用過github
所以想請叫一下是不是重新按upload 取代掉原本的檔案即算是繳交成功？
要交的檔案就是lex.l 以及 report嗎？

Ian Chen <notifications@github.com>於 2019年10月17日 週四，下午2:58寫道：

**Comment by ianre657** [comment]
@ysl19971124 
只你要確保自己 github 上面的版本是最新的就好。
我們會拿你死線到那一刻 repo 下面的那些檔案來批改 (或是在死線後有更動的版本，當然成績會直接打折)。

**Comment by ysl19971124** [comment]
助教您好
請問期中考是下禮拜三嗎
感謝🙏

Ian Chen <notifications@github.com>於 2019年10月25日 週五，下午4:17寫道：

**Comment by ianre657** [comment]
@ysl19971124 
對，順道一提，在課程網站首頁跟google calendar上面都有寫哦
