### ISSUE TITLE
樣板code編譯警告/ scanner.l 編輯 / yacc token

### ISSUE THREAD

**Issue by dd51108lai** [compiler-f19/Discussion#35]
@ianre657 @Naetw @YSHsieh7777
有3個問題想問助教
第一個是
![擷取](https://user-images.githubusercontent.com/55350819/67960426-3427ca80-fc35-11e9-96af-cdce2fd2c4c0.PNG)
請問直接拿去compile之後跳這個怎麼辦?

第二個是看講義上說的需要return值才能跑
所以是我們要自己在scanner.l裡補嗎?

第三個是想問一下
``
%token :=
``
是合法的嗎?

**Comment by Naetw** [comment]
同學你好

> 1. 請問直接拿去compile之後跳這個怎麼辦?

那些是警告，不會讓你的編譯失敗（但可能讓你程式出問題）。會有那些是因為助教的編譯參數使用了會輸出所有警告的選項 `-Wall`，可以試著練習看一下警告，並嘗試修復「由你撰寫出來的程式碼」所產生的警告，而上面的警告全部都是 `lex`, `yacc` 內部的實作所產生的，所以實際上不用理會。若同學覺得很煩可以去 `Makefile` 裡把參數 `-Wall` 移除。

> 2. 所以是我們要自己在scanner.l裡補嗎?

是的，這次需要修改 `scanner.l` 來跟 `yacc` 做配合。

> 3. `%token :=` 是合法的嗎?

可以先理解一下 `%token xxx` 會被 `yacc` 解讀並產生什麼樣的 C 程式碼。依照講義 Lec8 的 p.13 `%token xxx` 會產生出一個 C 的 macro，而 C 的 macro 名稱只能是 identifier，所以結論是不合法。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

TA

**Comment by Naetw** [comment]
補充：若想 tag 三位助教可以直接用 `@compiler-f19/2019-teaching-team` 來 tag。
