### ISSUE TITLE
Literal constant - 型別判斷超過 hw2 範疇

### ISSUE THREAD

**Issue by dd51108lai** [compiler-f19/Discussion#36]
@compiler-f19/2019-teaching-team 
抱歉又是我
我想問spec中

> where literal_constant is a constant of the proper type 

這句說需要proper type

>The part of semantic checking will be handled in the 4th assignment. In this assignment, you don't need to check semantic errors like "a := 3 + true;". Just take care of syntactic errors!

這句又說不需要解決語義問題
但我覺得所謂的proper type應該算是語義問題吧

這關係到要不要把type和constant寫死

*P.S. 我可以直接用1個討論串來問，暫時不要丟解決的TAG嗎?

**Comment by dd51108lai** [comment]
另外想問logical operator中的not要怎麼用啊?
not expression這樣嗎?

**Comment by ianre657** [comment]
@dd51108lai 同學可以一個問題開一個issue嗎？ 這樣其他同學比較好爬文

**Comment by Naetw** [comment]
同學你好

> 1. 但我覺得所謂的proper type應該算是語義問題吧

在常數變數的宣告上 spec 做了語法上的限制，也就是說在宣告常數變數的時候，常數只能是字面常數 (e.g., 100, 10.2, "aaaa")，不包含 expression，所以基本上也就沒有什麼 proper type 的問題，除非同學有想到什麼非 primitive type 的字面常數（助教目前想不到）。

> 2. not expression這樣嗎?

是。

> 3. 我可以直接用1個討論串來問，暫時不要丟解決的TAG嗎?

助教的建議是：你的標題請盡量切合當次想問的主題，以這篇來說就像是「常數變數宣告的 spec 定義」，若助教的回覆沒有解決你一開始的疑惑，那你可以再在下面留言繼續討論；若解決了，按個 emoji 助教會加上「已解決」的標籤。
若想把所有問題都放在同一串，那助教一開始大可直接開一個作業二討論串，但是助教認為這樣不好回覆、不好追蹤回答是針對什麼樣的問題，也可能會有要一直在同一串找有沒有更新以及自己是不是看過這個回覆的問題。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

TA

**Comment by ianre657** [comment]
@dd51108lai 

建議是一類問題就發一個 issue，算是替其他修課生著想，比較好搜尋問題。

同樣的角度來說，希望你未來的 issue 標題能寫的明確一些，以這個 issue 打比方，單純寫 "spec 問題" 有些太籠統，改成明確一點的內容會讓其他同學瀏覽時更快找到自己的問題，標體可以改成： "literal constant 中型別判斷超過 hw2 範疇"
