### ISSUE TITLE
Executing parser - 指令格式

### ISSUE THREAD

**Issue by dd51108lai** [compiler-f19/Discussion#38]
> Execute: ./parser [input file]

spec上的指令是這樣
但直接打進去之後好像沒反應
是要把[input file]換成什麼嗎?

**Comment by ianre657** [comment]
[input file] = 程式碼檔案名稱

**Comment by ianre657** [comment]
@dd51108lai 

[ input file ] = 想解析的程式碼檔案名稱，比如說你寫了一個 `P 語言`檔案叫做 `src.p`，裡面放了這次定義有關 P 語言的程式碼，你想要測試自己寫的 parser 針對這個 `P語言` 程式碼會如何解析，那麼就使用
`./parser src.p`，會寫 [ input file ] 是因為我們沒辦法知道同學想測試什麼檔案，所以就請同學自己填空，一個正常的流程會大概會像是 :

```shell
$ cd src && make
$ ls
Makefile    parser    src.p  ... (省略)
$ ./parser src.p
```

當然，這樣做會有點麻煩，不過也是往年編譯器課程的基本要求。今年我們有附上測試程式，裡面會幫你餵程式碼給自己寫的 parser 中，並與我們提供的正解比對。
同學可以採取 Test 的手段來直接查看輸出

+ Test: `cd test && python3 test`

我們期望同學這樣做起來會方便許多。
但如果想拿高分，請在通過基本測試之後自行撰寫 P語言程式碼，針對一些特殊情況進行人工測試

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

TA
