### ISSUE TITLE
Parser 沒有輸出資料

### ISSUE THREAD

**Issue by dd51108lai** [compiler-f19/Discussion#39]
@compiler-f19/2019-teaching-team 
如題
scanner中有return id :
```regex
    /* Identifier */
[a-zA-Z][a-zA-Z0-9]* { return id; }
```
parser中也有定義
```
%token id
```
但連第一個id都讀不到

output如下
```
1: /**
2:  * decl.p: declarations
3:  */
4: //&T-

|--------------------------------------------------------------------------
| Error found in Line #5: 
|
| Unmatched token: decl
|------------------------------------------------------------------------
```

真的是想不出來錯在哪了
想請問一下助教

**Comment by ianre657** [comment]
同學你好

雖然給的資訊不是很足夠，但我們已能大致通靈出你的問題了。但眼下解決 parser 沒有正確輸出反而不是重點。根據這篇 issue 以及 #38 來看，我認為你會在這裡無法繼續的原因是 - 你還沒理解  yacc 跟 lex 這些工具是怎麼跟你的程式碼整合在一起的。

lex , yacc 終究只是撰寫編譯器時的輔助工具，在不理解他們的前提下貿然使用必然會遇到不少問題。我給你的建議是 - **不要被工具給綁架**。你需要去查閱 lex, yacc 的文件，或是網路上的教學，並親自去看他們產生出來的 ` .c ` 檔案，看看產生的原始碼長什麼樣子，在這之後你就會知道這個問題怎麼解決了。

我會把這篇文章標記成 duplicate，理由是他跟 #38 背後的原因一模一樣。算是同學需要自主去學習的範疇。

**Comment by Naetw** [comment]
補充一下，lex 跟 yacc 的互動可以參考老師的講義 [lec8](https://github.com/compiler-f19/Compiler-f19-private/blob/master/LectureNotes/L8-Yacc.pdf) p.12，對你理解這次問題會有幫助。

**Comment by dd51108lai** [comment]
謝謝助教的高等通靈術
但是如果一執行就一頭撞進yyerror裡
error msg也沒說明是哪種error
根本無從debug
我認為這並不太像是不了解架構的問題

**Comment by ianre657** [comment]
你有沒有想過是你的變數命名錯誤？

**Comment by Naetw** [comment]
實際上是可以 debug 的，如果你知道 yacc 與 lex 之間的互動就會知道跑進 `yyerror` 之前會有哪些流程會先跑過，也就可以找到你的程式會跑進 `yyerror` 的原因。

**Comment by ianre657** [comment]
我把這個 issue 標記為 solved，因為太久沒人進行討論
