### ISSUE TITLE
simple statement 敘述問題

### ISSUE THREAD

**Issue by ran-ablaze** [compiler-f19/Discussion#40]
![image](https://user-images.githubusercontent.com/55475143/68541681-a9d22a00-03dd-11ea-9e17-fe83a92de1f6.png)
此處是否應修改為
` print variable_reference;`
or 
` print expression;`

**Comment by YSHsieh7777** [comment]
同學你好：
是的這裡就是你那個意思，
助教沒有排版好不好意思。
