### ISSUE TITLE
expression precedence 順序、interger_constant 判斷、expression 作為 statement 等問題

### ISSUE THREAD

**Issue by tracyliu1220** [compiler-f19/Discussion#42]
助教們好
關於 spec 我有幾個問題想問

### expression precedence 順序

spec 中有提到

> using the following operators with the precedence

請問是表格越上面越優先還是越下面呢

### interger_constant 判斷

for 迴圈的語法是

```
for identifier := integer_constant to integer_constant do
<zero or more statements>
end do
```

可是在作業 1 中有說 scientific notations 可以代表 decimal integers 或 floating-point numbers

請問意思是我們需要去改作業 1 的 code 判斷一個 scientific notation 代表 decimal integer 還是 floating-point number 嗎

### expression 作為 statement

因為 spec 上 expressions 被寫在 statements 的 section 下面

但是單純一個 expression 而且沒有分號可以做為一個 statement 感覺有點太神奇了

所以想特別問一下這樣是合法的嗎

**Comment by YSHsieh7777** [comment]
同學您好：

 > 1. expression precedence 順序

越上面越優先。

 > 2. interger_constant 判斷

作業一 Scientific Notations 敘述裡提到的 a decimal integer or floating-point number 指的是 aEb 中的 a 的部份，而不是整個 Scientific Notation 。

> 3. expression 作為 statement

expression 並不是一個 statement ，擺在這裡是因為上面的 simple statement 有 expression，這裡是助教沒有排版好不好意思。

---
若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

TA
