### ISSUE TITLE
integer constant 以及 integer literal 問題

### ISSUE THREAD

**Issue by tracyliu1220** [compiler-f19/Discussion#43]
請問 integer constant 相等於 integer literal 嗎？
不確定 integer constant 是否包含經過 constant declaration 的 integer

例如以下的例子不知道合不合法
先宣告成 constant 並在之後語意分析的部分對 a b 做是否 non-negative 的確認
```
var a: 1;
var b: 5;
for i := a to b do
end do
```
先感謝助教回答辛苦了

**Comment by Naetw** [comment]
同學你好

> 請問 integer constant 相等於 integer literal 嗎？

是。不包含 constant variable。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

TA
