### ISSUE TITLE
NONASSOC, YACC generating y.tab.h

### ISSUE THREAD

**Issue by tansr7** [compiler-f19/Discussion#44]
助教你好，

1. 關於 %nonassoc，投影片上有寫‘<’是不可以兩個連續用的，那請問‘=’可不可以兩個連續用？那別的relational operators也可不可以？

2. 關於 **makefile** 的yacc，直接 make 時，會提示沒有 y.tab.h ，因為 scanner.l 需要，暫時是使用 `yacc -d parser.y` 來生成 y.tab.h 和 y.tab.c。請問應該如何修改 makefile？

謝謝助教！

**Comment by Naetw** [comment]
同學你好

> 1. 關於 %nonassoc，投影片上有寫‘<’是不可以兩個連續用的，那請問‘=’可不可以兩個連續用？那別的relational operators也可不可以？

同學是想問在 P 語言能不能連續用嗎？如果是的話，因為沒有特別規定，所以你要讓它可以連續或是不要讓它可以連續都可以。另外投影片上指的 `<` 不能連續用是指 C（雖然助教看到的版本是該敘述有刪除線），跟本次作業的 P 語言無關。

> 2. 關於 makefile 的yacc，直接 make 時，會提示沒有 y.tab.h ，因為 scanner.l 需要，暫時是使用 yacc -d parser.y 來生成 y.tab.h 和 y.tab.c。請問應該如何修改 makefile？

既然需要加上 `-d` 這個選項來生成需要的檔案，那你就把這個選項也加進 Makefile 會執行的指令就好。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

TA
