### ISSUE TITLE
scalar_type問題

### ISSUE THREAD

**Issue by phlee1117** [compiler-f19/Discussion#45]
助教您好
![image](https://user-images.githubusercontent.com/8848185/68687765-a76ffb80-05a8-11ea-9777-62df5fc3adad.png)
這裡有提到 4 種 predefined 的 scalar_type 為 integer, real, string, and boolean，另一種唯一的 structured type 是 array
那是不是代表如果單純只寫 **type** 代表 **scalar_type** 或 **array type** 都算合法
而寫 **scalar_type** 代表只有 **scalar_type** 合法？

範例：
```
var identifier_list: **scalar_type**;
var identifier_list: array integer_constant to integer_constant of **type**; 
```
感謝助教

**Comment by Naetw** [comment]
同學你好

> 那是不是代表如果單純只寫 type 代表 scalar_type 或 array type 都算合法
而寫 scalar_type 代表只有 scalar_type 合法？

是。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

TA
