### ISSUE TITLE
expression 問題

### ISSUE THREAD

**Issue by nax1016cs** [compiler-f19/Discussion#47]
助教你好，

想請問expression中 連續兩個not或者兩個負號是合法的嗎?

例如: not not a, 或者 -- a。

謝謝助教!

**Comment by YSHsieh7777** [comment]
同學你好

因為 spec 中沒有特別規定，
所以這種連續的運算子語法同學讓它合法或不合法皆可，
測資中不會出現這樣的 expression

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
