### ISSUE TITLE
測試 - 標記所有同學

### ISSUE THREAD

**Issue by ianre657** [compiler-f19/Discussion#5]
# 起床摟
@compiler-f19/2019_students 
同學全不給我起來不要睡拉!
作業快要放下來拉
全部給我夾緊屁股去讀文件!

**Comment by ianre657** [comment]
@cmprfk2 沒收到訊息?

**Comment by cmprfk2** [comment]
全部標記的沒收到
我打開通知設定之後才看到，要測試一下
![Screenshot_20190709_201251](https://user-images.githubusercontent.com/52690318/60887021-f36f0480-a285-11e9-852a-752e16256b96.png)

**Comment by ianre657** [comment]
@cmprfk1呢?

**Comment by ianre657** [comment]
@cmprfk1 嗨?

**Comment by cmprfk1** [comment]
# 注意
要先去設打開選項之後被標記Github才會跳訊息

`Personal Settings` > `Notifications` > `Participating` > Web[打勾]

![Screenshot_20190709_201625](https://user-images.githubusercontent.com/52690250/60887281-890a9400-a286-11e9-8ede-7103a38e8206.png)

**Comment by ianre657** [comment]
現在1,2兩隻帳號應該都開啟web通知了
我在這裡重新標記一遍
@compiler-f19/2019_students

**Comment by cmprfk1** [comment]
有了，順道一題。
Github全新帳號的設定是傲有通知就會寄mail
但是github網站內對於repo的提醒不會打開
所以要記得去開web通知
