### ISSUE TITLE
[新手上路] TEEEEEEEEST

### ISSUE THREAD

**Issue by tommytyc** [compiler-f19/Discussion#5]
想問一下什麼時候才會被加進組織裡面ㄚ(´･ω･`)

**Comment by ianre657** [comment]
安安，剛剛我有先加一波了哦
![Screen Shot 2019-09-15 at 7 15 18 PM](https://user-images.githubusercontent.com/13212935/64920709-35b84300-d7ed-11e9-8605-8f167d4434b3.png)
