### ISSUE TITLE
[已打 patch] 作業二範例 code 會公布嗎

### ISSUE THREAD

**Issue by yenjushan** [compiler-f19/Discussion#50]
如題
想看看解答以免自己上一次作業的錯誤延續到作業 3 。

**Comment by Naetw** [comment]
同學你好

會的，預計這週末前連成績一併公布。由於作業開放遲交一週，今天才是最後的截止日，明天會進行批改。

作業二算簡單的，沒什麼複雜測資可以出，基本上同學有過助教給的 60 分測資就差不多了。作業三可以先動工。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by ianre657** [comment]
@yenjushan 
剛剛已經把範例程式碼發到同學的 repo 了
