### ISSUE TITLE
有關Makefile的修改 \ parser修改和執行流程

### ISSUE THREAD

**Issue by allen880117** [compiler-f19/Discussion#52]
助教您好
我有幾件事想確認一下
 1. 若我們想要用VP實做的話, 我們從一開始就必須使用C++來實做AST Node Class 對吧？ 
 2. 假設第一項問題沒錯的話, 我們就必須修改Makefile來支援g++的編譯對吧？
 3. 在parser裡面, 我們應該是在完整建造AST後, 在parser程式碼最下面的routine區call一個自己寫的dumpAST()來將AST的內容print到stdout上,這樣理解有錯嘛？

謝謝助教

**Comment by Naetw** [comment]
同學你好

> 1. 若我們想要用VP實做的話, 我們從一開始就必須使用C++來實做AST Node Class 對吧？

 Visitor pattern 只是一種設計的範式，沒有一定得綁定 C++，重點在於其中設計的巧思，所以要使用 C or C++ 都是可以的，不過助教的經驗是 C 會稍微麻煩一點，但掌控每個小細節的感覺也是不錯（？）考量到一些資料結構的實作複雜度，還是推薦使用 C++ 啦，另外同學使用 C++ 的話，以後 C++ 版本的範例程式碼助教就不用自己從頭寫了 (x

> 2. 假設第一項問題沒錯的話, 我們就必須修改Makefile來支援g++的編譯對吧？

是的。總之 Makefile 可以根據同學的需要進行任意的更改，只要助教在工作站上執行 `make clean && make` 可以正確無誤地執行完畢，且有 `parser` 這個執行檔的產生就行。

> 3. 在parser裡面, 我們應該是在完整建造AST後, 在parser程式碼最下面的routine區call一個自己寫的dumpAST()來將AST的內容print到stdout上,這樣理解有錯嘛？

沒錯。也就是說，在 `yyparse()` 跑完的同時，你的 AST 也建構完成了，後續的操作就直接針對 AST 去做。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
