### ISSUE TITLE
有關Declaration Node in Function Parameters 的 Location

### ISSUE THREAD

**Issue by allen880117** [compiler-f19/Discussion#53]
助教您好
在 Declaration Node 的 Spec 中
* Location : Line and column numbers of keyword var

然後在 Function Node 的 Spec 中
* Parameter : A list of declaration nodes (zero or more)

但是Parameter裡並不會有var這個關鍵字
直接參考function的Sample Solution，
好像是直接抓ID list中的第一個ID取代Var的Location資訊。
所以我們就比照操作就可以了嗎?

謝謝助教

**Comment by Naetw** [comment]
同學你好

> 所以我們就比照操作就可以了嗎?

是的，直接抓每個參數宣告的第一個字元位置就行。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
