### ISSUE TITLE
yacc $$ 回傳的資料型別

### ISSUE THREAD

**Issue by yenjushan** [compiler-f19/Discussion#54]
我在ast.h中定義了class AstNode，所有tree node都會繼承此class，希望以AstNode的指標traverse整棵樹。
我在parser.y中定義
```yacc
%{
 AstNode *ast 
} 
%type<ast> PromgramNode 
\\
root = new ProgramNode() ;
$$ = root ;
```
在make後的錯誤訊息是 "AstNode does not name a type"。
請問該如何正確定義$$.$1.....等的資料型態?

**Comment by Naetw** [comment]
同學你好

可以參考 [Yacc](https://github.com/compiler-f19/Compiler-f19-private/blob/master/LectureNotes/L8-Yacc.pdf) 講義 p.15, p.22：

## p.15

> Yacc can also support values of other types including structures
>   - Using `%union` in the declaration section

## p.22 Associating Union Member Names

```yacc
%union {
  int value;
  char *text;
  int optype;
  int nodetype;
}
```

- With terminals
  - `%token <value> NUM`
- With nonterminals
  - `%type <nodetype> expr stmt`

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by yenjushan** [comment]
助教回答的部分是用c的struct，若要用class，
%{
class AstNode *ast
}
同上，似乎加上class就可以跑過

**Comment by Naetw** [comment]
哦哦同學是使用 C++ 的話，因為助教自己沒有實作 C++ 版本，可以參考下 bison 的 [manual](https://www.gnu.org/software/bison/manual/html_node/A-Simple-C_002b_002b-Example.html)：

看起來直接用 `<>` 把你想要的型別放進去就可以了。
