### ISSUE TITLE
從何下手

### ISSUE THREAD

**Issue by YilingLin10** [compiler-f19/Discussion#56]
想請問四個程式分別要做什麼，`ast.h`, `ast.c`, `program.h`, `program.c`
（因為 `ast.h` 的 todo 只有在 astnode 的 struct 裡，那想請問其他的 node 是該定義在 `program.h` 嗎？）
還有visitor的class應該寫在program.h嗎？

**Comment by ianre657** [comment]
同學安安！

> 想請問四個程式分別要做什麼，ast.h ast.c program.h program.c

先澄清一點，我們 (正確來說是@Naetw) 給 starter code 的目的只是給個架構建議而已，實際上這堂課有多少學生就該有多少種實踐方式，所以沒有要求你要在這裡面做什麼動作 (想全部移除掉寫自己的也可以)

但如果是問 starter code 程式碼代表的目的，這倒是可以分享一下～
從資料夾的架構來看：

+ `src/` 實踐細節
	+ `AST/`: 放置 AST Node 的資料夾
		+ `ast.c`: AST Node 基礎型別的實踐
			以範例的 Animal 作為比喻，這裡會是 Animal 型別的實踐
		+ `program.c`: AST 中 `program` Node 的實踐
			以範例作為例子，這裡會是 `Cat` class 的實踐, 比如說他的 make_sound 方法 

+ `include/` 只放置 header file
	+ `AST/`
		+ `ast.h`: 給其他節點進行繼承的 AST Node 基礎型別
			對應到範例 animal.hpp 的 Animal 宣告
		+ `program.h`:  AST 中 `program` Node 的宣告
			對應到範例 animal.hpp 的 `Cat` 宣告
	+ `core/`
		+ `error.h`

要注意一下，這裡所謂的 `program.c` 並不意指一般寫 C 語言的 `main.c` ，而是我們在AST guideline 中所提到的 **`Program Node`**，以下是他的定義：
<details>
  <summary>Program Node 定義 (Click to expand!)</summary>

## Program Node

A program node should have the following information:

- Location
	- Line and column numbers of the program name
- Name
- Return type
- Global variable and constant declarations
	- A list of declaration nodes (zero or more)
- Function declarations
	- A list of function nodes (zero or more)
- Body
	- A compound statement node
- Location
	- Line and column numbers of the program name after keyword `end`
- End name
</details>

> 還有visitor的class應該寫在program.h嗎？

我們附上的程式碼都跟 visitor 無關，從我們給的程式碼中，同學會需要自己新增一個 visitor 的原始碼檔案進行實踐。

除此之外， 這份 starter code 並不是為 class 繼承所寫的，所以想寫繼承方式撰寫的同學或許可以在 `program.h` 額外使用 :
```cpp
#include "ast.h"
```

如果有進一步的問題，也可以附上你對這次作業的理解，讓我們代你檢驗一下自己的想法是不是對ㄉ

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by ianre657** [comment]
reference: #60 有附詳細教學
