### ISSUE TITLE
yacc - $$ 用途與形別

### ISSUE THREAD

**Issue by iamch15542** [compiler-f19/Discussion#57]
如果我在parser.y裡面定義
```
%union{
    char * text;
}

%token <sval> ID
```
然後我在scanner.l裡面
這樣使用
`yylval.text = yytext; return ID;`

最後在parser.y裡面
```
FunctionName:
    ID {$$ = $1;}
;
```
這樣 $1會是得到的字串是在scanner裡面切出來的對吧(?
然後他的型別則會是 char* (?

**Comment by YSHsieh7777** [comment]
同學你好:

正常來說會是 scanner 切出來回傳的 char* 沒錯，但是同學 <> 中的內容有誤，
建議同學參考 [Yacc](https://github.com/compiler-f19/Compiler-f19-private/blob/master/LectureNotes/L8-Yacc.pdf) 講義的 page 22

此外還有另一個可能會有問題的地方，
建議同學參考 [Yacc](https://github.com/compiler-f19/Compiler-f19-private/blob/master/LectureNotes/L8-Yacc.pdf) 講義的 page 16
同學應該可以發現有問題的部份

謝謝

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by ianre657** [comment]
其他點進這個 issue 的同學也可以參考 #54
