### ISSUE TITLE
原始碼檔案管理

### ISSUE THREAD

**Issue by javiersim** [compiler-f19/Discussion#58]
請問在[issue #56](https://github.com/compiler-f19/Discussion/issues/56)中有提到 "而在我們的實踐中，每一種program construct 都會建立一個 .c 檔案進行管理。" 是指每個new node的function都需要分開放在個別的.c檔嗎？

**Comment by Naetw** [comment]
同學你好

除了配分方式提到的 "Use visitor pattern to dump AST (+15 pts)" 以及 "get a 50-percent deduction if you pass any of our test cases without constructing an AST" 這類明確標示該怎麼做的說明同學需要遵守外，其他實作方式同學要怎麼去處理都沒有關係。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by ianre657** [comment]
以 program node 來說，
我們會寫一個 `program.h` 裡面放置 programNode  class 定義、Constructor 與 Destructor。也會有個 對應的 `program.c` ，其他 program construct 也照辦理。

不過你想怎麼做都可以，就像 @Naetw 說的，除了上面說的那兩項規定之外通過測資就是直接拿分，簡單又暴力。

**Comment by javiersim** [comment]
明白了，但還是想問好的寫法是將每個node都分開嗎？ 也就是 delcaration node, variable node也會有delaration.c和varaible.c

**Comment by ianre657** [comment]
我認為是的，因為節點的數量有點多，分開管理比較好閱讀
