### ISSUE TITLE
[已打patch]Expression Output

### ISSUE THREAD

**Issue by javiersim** [compiler-f19/Discussion#59]
Test cases 裡好像沒有 expression = ( expression ) 的例子，請問要用怎樣的 output format ?

**Comment by Naetw** [comment]
同學你好

`()` 只是用來影響計算的優先順序也就是影響 AST 的形狀，所以助教沒有特別設計額外輸出 `()`，而測資裡的確忘記測這件事，助教們會再討論看看要不要發 patch 或是留到第四份再進行測試。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by javiersim** [comment]
好像也沒有 expression = expression expression 的展開
那測資還會改嗎？

**Comment by Naetw** [comment]
"expression = expression expression" 不是合法的語法，同學指的是什麼呢？

就看有沒有發 patch，如果沒有這次測資就是這樣，但同學仍然要確保優先順序有被保留，否則第四份就會出現問題。

**Comment by javiersim** [comment]
抱歉是 expression = expression op expression op expression 比如 1+2+3

**Comment by Naetw** [comment]
像這類的 expression 若沒有優先順序（兩個都是加法）的話，樹的表達方法可以有兩種不同的形狀，但是計算結果會是相同的，所以助教認為沒有必要去測，同時這也會造成批改上的麻煩。

**Comment by Naetw** [comment]
由於繳交期限延後，晚點會發 patch，裡面包含繳交期限的更新與新增 `()` 的測資。
