### ISSUE TITLE
HW3 死線延期，C++教學說明

### ISSUE THREAD

**Issue by ianre657** [compiler-f19/Discussion#60]
@compiler-f19/2019-students 

各位同學安安，
想必大家都有收到先前 E3 寄信的作業三問卷調查

除了得知同學最近生活有點困難，作業三的開始指引不夠明確之外，
我們還注意到了 :
### ~高達 21.7%  的同學希望告訴教授實驗室缺衛生紙~

好的，進入正題，在收到回應之後我們做了兩個決定：

---

### 死線延期

在考慮同學狀況後，我們決定將 HW3 死線從 12/4 (三) 23:59 延後到 12/8(日) 23:59 ，但考慮到作業四的發布時程，作業三在 12/10(二) 23:59 之後就不再接受遲交，請各位同學注意。

### 簡易教學

再來，我預計這個週末會開直播帶領同學使用 C++ 撰寫 hw3 到成功建立第一個 Node 為止，希望同學能夠在學完之後還有一個週末可以趕進度，由於我自己也有事情，等準備好環境後會在這個討論串中通知大家。

+ [code repo](https://github.com/compiler-f19/hw3-cpp-startercode)
+ [影片連結](https://youtu.be/AjRdL8lxj5k)

豪，大概就是這樣
希望大家也可以有多點時間完成微處理機跟準備其他科目期中

![1575091095186](https://user-images.githubusercontent.com/13212935/69895939-eb6a4b00-1373-11ea-81d4-d7cb10866737.jpg)

**Comment by dd51108lai** [comment]
直播是什麼時侯阿
可以斗內嗎

**Comment by ianre657** [comment]
真假有乾爹哦
目前卡在麥克風動不起來
可能會是直播或是拍影片吧

**Comment by tommytyc** [comment]
助教辛苦ㄌQQQ

**Comment by zzycc** [comment]
助教辛苦了QQ

**Comment by ianre657** [comment]
因為直播環境搞不定，所以決定拍影片
現在正在整理要講什麼東西，今晚或明早會放上來連結，到時候再通知大家

**Comment by ianre657** [comment]
@compiler-f19/2019-students 
安安
影片已經拍完了，目前 youtube 正在處理中。
我先附上我在影片中寫的程式碼

[hw3-cpp-startercode](https://github.com/compiler-f19/hw3-cpp-startercode)

只有組織內的人才有閱讀權限

**Comment by ianre657** [comment]
做個reference: #56
