### ISSUE TITLE
function declaration 中 array 變數的意義

### ISSUE THREAD

**Issue by zzycc** [compiler-f19/Discussion#61]
在README的Simple sample中的function declaration
func( a: integer ; b: array 1 to 2 of array 2 to 4 of real ): boolean;
在traverse的過程會輸出
function declaration <line: 4, col: 1> func boolean (integer, real[1][2])
小弟資質駑鈍QQ
我沒看懂 real[1][2]
1、2代表什麼意思

**Comment by Naetw** [comment]
同學你好

就是類似 C 陣列型別，1 to 2 代表 [1, 2)，所以有 1 個元素；2 to 4 代表 [2, 4)，所以有 2 個元素。所以整個 b 的型別就會是 `real[1][2]`。

不過有個狀況是前面的數字大於後面的數字，這個因為助教沒有定義清楚該怎麼輸出，同學可以先不考慮這樣的狀況。之後第四份會需要同學找出這樣的錯誤，到時助教不會把 AST dump 出來比對。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
