### ISSUE TITLE
test.py 無法正常輸出

### ISSUE THREAD

**Issue by dd51108lai** [compiler-f19/Discussion#62]
助教你好
我在使用Execute或test指令時
他都只會跳出
> Usage: ./parser \<filename\>

我跟python不太熟
看不太懂test.py
請問要怎麼解決這個問題呢?

**Comment by Naetw** [comment]
同學你好

這個錯誤訊息是來自你的 parser，若你沒有動過 `test` 底下的東西，`test.py` 正常來說不會有問題。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by Naetw** [comment]
還有一個可能是你在 `parser.y` 的 `main` 裡處理 `--dump-ast` 的時候沒有處理好順序的問題，因為目前 `test.py` 是預設直接把 `input file` 當做 `./parser` 後第一個參數，然後 `--dump-ast` 會當成第二個餵進去給你的 `parser`。你可以注意一下看是不是順序造成的問題。

**Comment by dd51108lai** [comment]
所以說我應該要在parser.y的main裡面處理 --dump-ast 嗎
我以為指令的部分是 test.py 幫忙處理的

**Comment by dd51108lai** [comment]
謝謝助教
自己再來debug看看

**Comment by Naetw** [comment]
對，畢竟輸出 ast 的是你的 parser，所以參數 `--dump-ast` 應該要由你的 parser 處理。
