### ISSUE TITLE
[BUG]  hw3-cpp-startercode 的 ast.hpp 有點小錯

### ISSUE THREAD

**Issue by a04775** [compiler-f19/Discussion#63]
首先，先感謝助教半夜兩點還在錄製影片幫助我們😘。

但是半夜兩點可能比較神智不清，不宜寫code。

大家要注意第九行有個小錯，應該改成：
Location(uint32_t line, uint32_t col) : line(**line**), col(col){};
不要跟我一樣找很久哦 > <

<img width="1158" alt="螢幕快照 2019-12-02 下午6 34 57" src="https://user-images.githubusercontent.com/35053152/69952995-51e99780-1533-11ea-9e06-c0dc3b297291.png">

**Comment by ianre657** [comment]
哈哈 我再改一改
感謝

**Comment by ianre657** [comment]
就留著吧，讓不小心貼錯的其他同學能快點 debug
