### ISSUE TITLE
有關 Bonus 的問題 / Valgrind 的使用

### ISSUE THREAD

**Issue by allen880117** [compiler-f19/Discussion#65]
助教您好
請問一下 Bonus 的 Memory Leak 的問題

因為我是第一次使用 valgrind , 所以我並不是很確定這樣使用是否正確
這是我目前下的指令
```
#!/bin/bash
valgrind --leak-check=full --show-leak-kinds=all -v  ./parser $1 --dump-ast
```
其中 `$1` 是 `/test/test-cases/` 中的測資
而以下是我把全部我想得到可以free且不要亂free之後的結果
另外我也試著用某些方法把flex的memory leak想辦法清掉了（大概）
```
==3716== 
==3716== HEAP SUMMARY:
==3716==     in use at exit: 0 bytes in 0 blocks
==3716==   total heap usage: 89 allocs, 89 frees, 99,412 bytes allocated
==3716== 
==3716== All heap blocks were freed -- no leaks are possible
==3716== 
==3716== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
==3716== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```
請問這樣有清乾淨嘛？

**Comment by Naetw** [comment]
同學你好

> 所以我並不是很確定這樣使用是否正確

助教也是使用同樣的指令來做檢查。

> 請問這樣有清乾淨嘛？

哦哦其實 `flex` 不用處理沒關係的，畢竟不是你寫的程式 XD 只要確保你寫的部分沒有 memory leak 問題即可。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
