### ISSUE TITLE
traverse Constant Node 問題(String)

### ISSUE THREAD

**Issue by zzycc** [compiler-f19/Discussion#66]
助教你好
我看到ConstantValue的 test case給 string 的答案 是有""
範例裡面是
var cs : "muda muda muda muda!!!";
sample output是
      constant <line: 7, col: 10> "muda muda muda muda!!!"

請問
String 的value是直接把scanner掃描的結果直接輸出
不用把第一次作業的字串處裡的結果輸出??(像多個引號的問題)

還是說 是把字串處裡完的結果 在左右邊加上"

**Comment by Naetw** [comment]
同學你好

直接在處理完的結果左右兩邊加上 `"` 即可。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
