### ISSUE TITLE
Dumping arguments of function node.

### ISSUE THREAD

**Issue by Vamesix** [compiler-f19/Discussion#67]
In the test case function.p, this line
`func2(a: array 1 to 2 of array 2 to 4 of boolean): boolean;`
outputs this
`function declaration <line: 11, col: 1> func2 boolean (boolean[1][2])`
But shouldn't it output something like
`function declaration <line: 11, col: 1> func2 boolean (boolean[1...2][2...4])`

**Comment by Naetw** [comment]
TAs may discuss whether that difference is necessary, but it's not appropriate to change the spec nowadays. Just follow the solution of the test case, thanks!

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
