### ISSUE TITLE
關於如何建list of nodes

### ISSUE THREAD

**Issue by tommytyc** [compiler-f19/Discussion#68]
像是在programbody底下可以看到的 `a list of declaration nodes` ，
因為一開始沒發現yacc好像不支援vector，
現在有點不太確定有沒有比較好的建立a list of a kind of node的方式＠＠
想請問助教有推薦的方式嗎？

**Comment by Naetw** [comment]
同學你好

這次我們是使用 `bison`，而 `bison` 確定可以使用 vector 喔，可參考[連結](https://www.gnu.org/software/bison/manual/html_node/A-Simple-C_002b_002b-Example.html)。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by tommytyc** [comment]
感謝助教！
