### ISSUE TITLE
test.py輸出

### ISSUE THREAD

**Issue by YilingLin10** [compiler-f19/Discussion#71]
與 #62 遇到相同的問題，但不清楚怎麼修改參數，或該怎麼解決

**Comment by Naetw** [comment]
請在你的 `main()` 裡面判斷是否有參數 `--dump-ast` 傳入。可參考[連結](https://www.geeksforgeeks.org/command-line-arguments-in-c-cpp/)。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by YilingLin10** [comment]
檢查後有--dump-ast傳入,argc==3，但仍然只會跑出 "Usage: ./parser <filename>\n"
請問需要對"--dump-ast"做什麼處理？

**Comment by Naetw** [comment]
> 檢查後有--dump-ast傳入,argc==3，但仍然只會跑出 "Usage: ./parser \n"

請去檢查印出那串的條件。

> 請問需要對"--dump-ast"做什麼處理？

Your parser should dump the AST when the flag --dump-ast is enabled.

**Comment by ianre657** [comment]
@YilingLin10  
直接拿 `test.py` 中呼叫你程式的輸入的程式碼來看：

```python
clist = [self.parser, test_case, "--dump-ast"]
        cmd = " ".join(clist)
        try:
            proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True)
```
可以看出來
argv[0] -> 程式名稱
argv[1] -> 要讀取的程式碼檔案名稱
argv[2] -> 我們會下 --dump-ast

你可以檢查一下照這個格式輸入時，你的程式能不能正確吃到參數
