### ISSUE TITLE
dumpvisitor.cpp裡面的accept

### ISSUE THREAD

**Issue by TOMxLEON** [compiler-f19/Discussion#75]
<img width="1280" alt="Untitled" src="https://user-images.githubusercontent.com/42515822/70514009-b200bf00-1b6d-11ea-8764-038511df036f.png">
如圖，請問為什麼我照著教學的方式寫，在dumpvisitor.cpp裡的accept就認不得這個this要怎麼visit？

**Comment by Naetw** [comment]
同學你好

可以檢查看看你的 `FunctionNode`, `CompoundStatementNode`, `VariableNode` 有沒有去實做虛擬函式 `accept`。錯誤訊息很明確地說編譯器找不到對應的 `xxxxNode::accept` 函式。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
