### ISSUE TITLE
Pseudo Comment / Semantic Error / Multi-pass / 的疑問

### ISSUE THREAD

**Issue by allen880117** [compiler-f19/Discussion#77]
助教您好

我想問幾個問題
* 我們建立 Symbol Table 的時間點應該是在AST完成後 
* 但好像和Pseudo Comment的用途衝突，下面說明
* Spec上有關Pseudo Comment的這段有點看不太懂
```
Dump the contents of the symbol table associated with a block when exiting from that block.
```
  block 是指一個 scope 嗎，還是指整個Program包圍起來的部分?
  若需要支援這個Pseudo Comment在文本開頭以外的地方進行開關，
  以我想到的實作方法而言，我只能在Parser建立AST時也一併建立Symbol Table並輸出，
  不能在Parse完後輸出，因為此時已經沒有Comment的資訊了(除非我將它併入回傳的資料結構中)。
* 另外一個問題是 (我英文不太好)
```
Note that once your parser has found a semantic error in a child node of an AST node, the parser doesn't check semantic errors related to the child node of the AST node.
```
  是指不用再檢查此child node的child node嗎?
* 最後想問一下 Multi-pass明確來說是要達到怎樣的成果(或是實作方式)才是Multi-pass?

謝謝助教

**Comment by Naetw** [comment]
同學你好

> block 是指一個 scope 嗎，還是指整個Program包圍起來的部分?

是指一個 scope。也就是說，你在 `popScope` 的時候如果開關是開的，就要把 table 印出來。

> 若需要支援這個Pseudo Comment在文本開頭以外的地方進行開關

對，其實這是以前實作方法可以做到的事情，但是為了語意錯誤的順序統一，所以我們建了 AST，也因此同學只需要考慮開頭的時候有沒有把 D 這個 pseudocomment 做開關就行了，不用考慮它在中間出現的可能性。這邊是助教疏忽沒有明確提到這點。

> 是指不用再檢查此child node的child node嗎?

不是。舉個例子：

一個 assignment 會有兩個子節點，`lvalue` 以及 `expr`，根據語意分析順序的要求，也就是 post-order，`lvalue` 以及 `expr` 這兩個子節點會先被分析過後，才會輪到 assignment 本身。所以上面那段的意思是：若任一子節點，在這是 `lvalue`、`expr` 有語意錯誤發生，我就不用檢查在 assignment 相關的錯誤中，與發生錯誤的子節點有關的錯誤。像是若 `expr` 有誤，那我就不用檢查 `lvalue` 與 `expr` 的型別是否相符（因為有誤，無法判斷）。

> 最後想問一下 Multi-pass明確來說是要達到怎樣的成果(或是實作方式)才是Multi-pass?

你的 symbol tables 可以被多個 visitor 使用。舉例來說，你在 semantic analyzer 裡面建構了這支程式的 symbol tables，然後語意分析做完之後，只要你的 semantic analyzer 這個物件留存著，你可以把 symbol tables 傳出去給別的 visitor 去使用，像是 optimizer 或是 code generator 等等。

簡單來說你在 `popScope` 的時候，實際上只能讓這個被 pop 掉的 symbol table 隱形，不能整個刪掉，之後要能夠重複使用。

---

@compiler-f19/2019-students 同學好，注意一下！

關於 symbol table dumping 的 pseudo comment 只需要考慮它出現在 source program 的開頭即可，也就是你在建構完 AST 之後就會確定這次要不要進行 dump，而不用去考慮說同一支程式中某段程式會需要 dump，而另一段程式不需要。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
