### ISSUE TITLE
語法錯誤的宣告是否放入 Symbol Table 的疑問 / 錯誤訊息輸出的順序

### ISSUE THREAD

**Issue by allen880117** [compiler-f19/Discussion#79]
助教您好
假如說variable的宣告有錯, 如array的upperbound比lowerbound小
或是program 的名稱和檔案名稱不符合
那還需要將其放入Symbol Table中嗎?

因為test-case提供的情況都是將Symbol Table和Semantic Check分開來測試的情況
所以像這種絞在一起就有點難去想說怎樣去做。

另外一個問題是，Redeclare和Semantic Error兩種錯誤訊息的輸出是交錯輸出還是有何種優先順序?

**Comment by Naetw** [comment]
同學你好

> 假如說variable的宣告有錯, 如array的upperbound比lowerbound小
或是program 的名稱和檔案名稱不符合
那還需要將其放入Symbol Table中嗎?

兩者界線有點模糊，但是可以這樣去想：

Symbol table 只負責把 symbol 放進去，所以它只檢查放進去的東西是否重複；而 array 的大小合法性屬於後續 semantic check 的範疇，所以不影響放不放入，但是會影響後續與該 variable 相關的語意檢查。

> 另外一個問題是，Redeclare和Semantic Error兩種錯誤訊息的輸出是交錯輸出還是有何種優先順序?

Spec 有說明在巡訪整棵 AST 時，symbol table 建構與語意檢查的順序:

> In summary, you need to implement the construction of symbol tables and semantic analyses based on the AST you constructed in the previous assignment by traversing the AST in preorder and postorder, respectively.

例如 starter code 裡 `analyzeProgramNode` 裡面行為順序是這樣：

```
// symbol table construction
// visit child nodes
// semantic checks
```

因此，基本上你每個 `visit` 函式中，都依照這樣的順序規範去實作，基本上不會需要考慮輸出順序的問題，遇到錯誤就直接輸出就行了。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by allen880117** [comment]
那請問array size在symbol table 中要顯示負值嗎
(upperbound < lowerbound)

**Comment by Naetw** [comment]
> 那請問array size在symbol table 中要顯示負值嗎

對，看你實作方便的話，就直接把相減的結果印出來就好，若你是設計用 unsigned 存也沒關係，因為這邊的一些設計還沒有很完善，到時候批改 symbol table construction 的部分也不會有這樣的測資。
