### ISSUE TITLE
想確認完成的順序

### ISSUE THREAD

**Issue by dd51108lai** [compiler-f19/Discussion#80]
應該是先完成建立 symbol table 的visitor
再用 semantic analyzer 去檢查 symbol table嗎?
看spec要求應該是這樣
但是看test case好像是要在檢查完型別之後再做symbol table
若是會跳error的似乎不會放進symbol table中
不太懂確切的流程

**Comment by Naetw** [comment]
同學你好

> 應該是先完成建立 symbol table 的visitor
再用 semantic analyzer 去檢查 symbol table嗎?

這是其中一種做法，但這種做法你會需要設計用於 multi-pass 的 symbol table，關於 multi-pass 可見 https://github.com/compiler-f19/Discussion/issues/77#issuecomment-565493802 。

助教自己的做法是 multi-pass 版但是 symbol table 的建構與語意檢查都是放在 semantic analyzer 裡面。流程可以參考一下 C 版本 starter code 裡面的註解，應該對於理解有些幫助。

> 但是看test case好像是要在檢查完型別之後再做symbol table

symbol table 的建立就是要幫助後面的型別檢查，倒著做是件很怪的事。

> 若是會跳error的似乎不會放進symbol table中

spec 中有提到：

> Name must be unique within a given scope.

所以重複宣告的 symbol 當然不能放進去。另外我想這個疑問其實在另一個 issue 有被討論過了：https://github.com/compiler-f19/Discussion/issues/79#issuecomment-565710292 建議發 issue 前可以先看看有沒有類似的問題被問過了，若還是無法解決疑問再來針對不理解的點去發問，可以省下發問以及回答「重複問題」的時間。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by dd51108lai** [comment]
我比較有疑問的部分是既然symbol table的建立是在語意檢查之前
那要如何在建立的當下得知目前放入的symbol是合法或非法?
應該是在語意檢查發現有錯時才會把錯誤的symbol刪掉才對吧

**Comment by Naetw** [comment]
> 那要如何在建立的當下得知目前放入的symbol是合法或非法?
應該是在語意檢查發現有錯時才會把錯誤的symbol刪掉才對吧

若在設計上把「symbol table 的建立」與「語意檢查」的行為完全獨立分開，的確就無法在放入的當下檢查。

現在想想這的確是作業 4 可以重新設計的部分，由於往年作業 4 是分開的，分成 symbol table 與 semantic definition，而當時是把「重複宣告」分在 symbol table 建構時去做的，因此這次合併與實作時也沒有多想就直接照舊。

因此若要分開的話，跟 symbol table 有關的測資會失敗，所以麻煩同學若有分開設計，在報告中註記一下，我會額外批改。

至於 spec，我們會再討論之後是否把這部分重新設計成完全獨立，但是在這學期因為時間關係不會做這樣的更動，還請同學見諒。

**Comment by dd51108lai** [comment]
我還是不太理解為何以我的寫法會出錯
輸出到stdout的時點應該是pop table的時候才對
若是出錯是哪一個部分會出錯呢
可以舉個例說明一下嗎

**Comment by Naetw** [comment]
啊啊同學抱歉，我把它想成作業拆開的狀態了 Orz
這樣的話，分開實作不用特別標註。
