### ISSUE TITLE
Loop variable

### ISSUE THREAD

**Issue by javiersim** [compiler-f19/Discussion#81]
The spec states :
> The value of the loop variable cannot be changed inside the loop.

but how do we know it is a loop variable?
Should we add an attribute into the symbol table?

**Comment by Naetw** [comment]
> Kind: The name type of the symbol. There are six kinds of symbols: program, function, parameter, variable, loop_var, and constant.

The field "Kind" in the symbol entry includes the type 'loop_var' which can represent a loop variable.

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by javiersim** [comment]
Oh okay, I was going through those test cases and did not notice that sorry my bad.
