### ISSUE TITLE
Position for '^'

### ISSUE THREAD

**Issue by javiersim** [compiler-f19/Discussion#82]
I would like to ask about the position for '^' in some cases

` int := stringgg+stringg ; `
when assignment of different types but the rvalue is a binary expression, should it be on the first operand?

` if 10 + 10 then `
when conditional expression is a non boolean binary expression, why is it put under '+'? Shouldn't it check the expression first, where it is valid in this case, then only found that the expression result in an integer type? Am I misunderstanding the order of the semantic analyzer?

**Comment by Naetw** [comment]
> when assignment of different types but the rvalue is a binary expression, should it be on the first operand?

It should be the position of `BinaryOperatorNode`.

> when conditional expression is a non boolean binary expression, why is it put under '+'? Shouldn't it check the expression first, where it is valid in this case, then only found that the expression result in an integer type? Am I misunderstanding the order of the semantic analyzer?

No, you aren't.
The expression here is a binary operator node, that's why it uses the position of "+".
Remember that we don't have an explicit definition of `ExpressionNode` in hw3. So, when there is a semantic error related to an expression, the position of it depends on what kind of node it is precisely.

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by javiersim** [comment]
So in this case which node will we find the error ?
` if 10 + 10 then `

**Comment by Naetw** [comment]
> So in this case which node will we find the error ? `if 10 + 10 then`

`IfNode`. We have defined what semantic errors should be checked for each AST node in `error-message.md`.

**Comment by javiersim** [comment]
That the thing I don't understand, if we found it in IfNode how do we know there is a '+'.

**Comment by Naetw** [comment]
In the hw3, we have defined that an `IfNode` has a node for condition, and each node owns the position info. You can just use it.

**Comment by javiersim** [comment]
Then what if it was a `1+2+3+4+5` statement, where should we put it ?

**Comment by Naetw** [comment]
Whatever your node of condition records. It depends on how your yacc rules work.
