### ISSUE TITLE
Order of stdout

### ISSUE THREAD

**Issue by javiersim** [compiler-f19/Discussion#83]
The spec states :

> Dump the contents of the symbol table associated with a block when exiting from that block.

but on test case "error.p" line 7 has redeclared variable p1 inside the block so mine will print out semantic error before dumping symbol table which is different from sample solution where all symbol table is dumped before any semantic error.

Do we have to save all semantic error to print after symbol table?

**Comment by Naetw** [comment]
You just need to dump the symbol table to `stdout` and the error msg to `stderr`. Then the mechanism of buffering and out test script will take care of it.

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by javiersim** [comment]
I tried to print with `fprintf(stderr, "%s\n", string)` but still unable to print with order.
Is that how you print to stderr?

**Comment by Naetw** [comment]
Yes.
It’s because the non-buffering mechanisms of `stderr`. We have handled that in the test script.
