### ISSUE TITLE
錯誤訊息的輸出及順序

### ISSUE THREAD

**Issue by yenjushan** [compiler-f19/Discussion#85]
助教您好:
請問同一個節點語意分析的錯誤訊息是要全部印出來還是只要找到一個錯誤訊息印出就好。若只要印出一個錯誤訊息，錯誤訊息的順序又有何規定?

以VariableReference的測資為例:

10:         print arrrrrrr["SSLAB"]["No.1"];

這行的錯誤訊息只有

<Error> Found in line 10, column 15: use of undeclared identifier 'arrrrrrr'
            print arrrrrrr["SSLAB"]["No.1"];
                  ^

所以下列這類的錯誤訊息就不用再輸出了嗎?
<Error> Found in line x, column y: index of array reference must be an integer
     read a["SSLAB"];
            ^

**Comment by Naetw** [comment]
同學你好

> 1. 請問同一個節點語意分析的錯誤訊息是要全部印出來還是只要找到一個錯誤訊息印出就好。若只要印出一個錯誤訊息，錯誤訊息的順序又有何規定?

能判斷的全都要，無法判斷的則像是 Spec 中提到的：

> Note that once your parser has found a semantic error in a child node of an AST node, the parser doesn't check semantic errors related to the child node of the AST node.

同一個節點錯誤的順序在 `error-message.md` 有提到：

> Each check inside a node should be performed in the order as described.

而不同節點間則是在 `README.md`：

> In summary, you need to implement the construction of symbol tables and semantic analyses based on the AST you constructed in the previous assignment by traversing the AST in preorder and postorder, respectively.

> 2. 所以下列這類的錯誤訊息就不用再輸出了嗎?

一個未定義的 identifier 你無法知道它的型別，因此我們不需要去判斷後續行為。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by tracyliu1220** [comment]
啊我還想再問一個

那 refers 到一個 index 有問題 array declaration 的 variable reference

也不能噴 undeclare error 嗎？還有這個 variable reference 的 subscript 也不用檢查？
