### ISSUE TITLE
array reference

### ISSUE THREAD

**Issue by iamch15542** [compiler-f19/Discussion#86]
助教您好，
想確認一下說
array reference一定要是 integer 對不對？ 
就是要a[113], b[234] 這些才能算是合法的
而a[1 + 1], b["ss"], c[func()] 這些都要算是不合法的對吧！？
就算他們回傳值是 integer 也是？
然後以上的錯誤都是輸出
`<Error> Found in line x, column y: index of array reference must be an integer`？

**Comment by Naetw** [comment]
同學你好

> array reference一定要是 integer 對不對？

對。

> 就是要a[113], b[234] 這些才能算是合法的
而a[1 + 1], b["ss"], c[func()] 這些都要算是不合法的對吧！？

錯。只要他們的回傳值也是 integer 就合法。

> 然後以上的錯誤都是輸出
<Error> Found in line x, column y: index of array reference must be an integer？

對，錯誤訊息請參考 `error-message.md`。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by iamch15542** [comment]
助教您好，
想再問一下說，
如果已經發現`index of array reference must be an integer`這種的錯誤
是不是就不用檢查說有無`over array subscript`了，因為我看readme是說不會繼續往下檢查？
同時我們只需要管說裡面是不是integer，而不用管大小是否有超出範圍？

**Comment by Naetw** [comment]
> 是不是就不用檢查說有無over array subscript了，因為我看readme是說不會繼續往下檢查？

是。

>   若是發現index of array reference must be an integer是指在那個index對吧?

是。

> 同時我們只需要管說裡面是不是integer，而不用管大小是否有超出範圍？

是。
