### ISSUE TITLE
Variable Reference and Scope

### ISSUE THREAD

**Issue by phlee1117** [compiler-f19/Discussion#87]
readme提到
compound statement內的inner scope是看不到outer scope的symbol的

如果是Variable Declaration的話，是不是代表inner scope可以跟outer scope的variable name重複？
另外有三種情況想問
1. global
global和local的variable名字可以重複，蠻合理的
2. loopvar
loopvar在inner不能重複，這已經有確實註明
3. parameter
如果Function裡面的inner scope有Variable跟parameter重複名字，感覺蠻奇怪
範例如下
```
fun( a, b : integer; c : string ) : integer;
begin
    // 這裡不能有a或b或c的declaration，因為當前scope已經有了
    begin
        // 但這裡呢？？？
    end
end
end fun2
```

Variable Reference的方面也是類似上面，三種情況想問
1. global variable只有在global scope被referenced才合法嗎，還是任何local scope都要能看到
(因為C是如此，readme也沒特別提到global)

2. loopvar在loop內可被referenced嗎？
readme有寫不能被modified，那讀取呢？
例如print或是某些expression運算

3. function的parameter在function內可被referenced嗎？

**Comment by Naetw** [comment]
同學你好

> 如果是Variable Declaration的話，是不是代表inner scope可以跟outer scope的variable name重複？

是，就跟你寫 C/C++ 規則類似。

> 但這裡呢？？？

可。你可以把 parameter 的宣告想成在函式主體（第一個 begin end）做的，所以再往內一層就是 inner scope，可以蓋掉。

> global variable只有在global scope被referenced才合法嗎，還是任何local scope都要能看到
(因為C是如此，readme也沒特別提到global)

任何地方都要看到，但是 local 可以蓋掉 global reference，跟 C 一樣。

> loopvar在loop內可被referenced嗎？

當然可以，不能修改而已。

> function的parameter在function內可被referenced嗎？

可以。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by phlee1117** [comment]
所以loop var和parameter
若分別在for和func內，即使在不同scope也要能被referenced對吧？例如在裡面的另一個compound內部

**Comment by Naetw** [comment]
對。
