### ISSUE TITLE
Print Node

### ISSUE THREAD

**Issue by phlee1117** [compiler-f19/Discussion#88]
eror-message.md中Print Node的部份寫到
* Print Node
    * Variable reference in the print statement must be scalar type.

但Print後面接的是Expression Node
如果後面接的是Function Call Node，是不是就不用檢查這個semantic error了呢？
畢竟Function Call可能沒有回傳值 (procedure call)

**Comment by Naetw** [comment]
同學你好

print node 這邊的確是 spec 描述不清，請直接判斷後面接的 expression node 型別是否為 scalar，這樣應該會比較好實作，不用特意去判斷當前的 expression node 是不是 variable reference。

雖然助教看目前完成的幾位都是直接去判斷 expression node，但考量可能有同學會依照 spec 現有不清楚的標示去實作，這次助教不會測試 variable reference 以外非 scalar 的測資。但是像是 operator 測資那些在 expression node 本身就發生問題的測資還是會有，畢竟這樣其實 print node 會跳過檢查。

感謝同學 debug。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
