### ISSUE TITLE
關於semantic error

### ISSUE THREAD

**Issue by Joechiaotung** [compiler-f19/Discussion#89]
`arr[ "SSS" * arrr[5][8] ]`
1.如果已知 arrr[5][8] 這個 variable reference 有誤，那是否還要印出關於`"SSS" * arrr[5][8]`這個expression的錯誤，因為即使只看前面`"SSS" *`也是錯誤的
`Note that once your parser has found a semantic error in a child node of an AST node, the parser doesn't check semantic errors related to the child node of the AST node.`
2.根據上面敘述，我是否還需要檢查 arr 這個 variable reference 有關於裡面這個 expression `"SSS" * arrr[5][8]` 的錯誤 ?

**Comment by Naetw** [comment]
同學你好

> 如果已知 arrr[5][8] 這個 variable reference 有誤，那是否還要印出關於"SSS" * arrr[5][8]這個expression的錯誤，因為即使只看前面"SSS" *也是錯誤的

因為 spec 說了：

> Note that once your parser has found a semantic error in a child node of an AST node, the parser doesn't check semantic errors related to the child node of the AST node.

而 binary operator `*` 的 child node 也就是 variable reference 錯了，所以 binary operator `*` 直接跳過檢查。

>  根據上面敘述，我是否還需要檢查 arr 這個 variable reference 有關於裡面這個 expression "SSS" * arrr[5][8] 的錯誤 ?

同上。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
