### ISSUE TITLE
Type Coercion and Comparison

### ISSUE THREAD

**Issue by iamch15542** [compiler-f19/Discussion#90]
助教您好，
想詢問一下README裡面這段的意思，因為有點不懂
> Two arrays are considered to be the same type if they have the same number of elements. More specifically, they have the same number of dimensions and the same size for each dimension and the type of element is the same.

我的理解是兩個arr要相同的話得各個元素大小都一樣，像是

> var arr : array 3 to 6 of array 3 to 6 of integer;
> var arr1 : array 4 to 8 of array 3 to 6 of integer;
> var arr2 : array 1 to 4 of array 4 to 7 of integer;

這樣是不是 只有 arr 跟 arr2 是一樣的，然後 arr 跟 arr1 是不相同的？
如果 arr[1]跟 arr1[3] 這樣也是一樣的嗎？
還是說是其他的意思，而我想錯了？

另外想問一下
如果 func() 是redeclared的，是不是就不用檢查他的參數以及compound有沒有問題了？
同上，如果是func的參數redeclared，是不是也不用再檢查compound有沒有問題了？
和 

>var arr : array 80 to 80 of integer;

是合法的對吧(？
以及 for的loop_var是可以被拿來引用的對吧？只是不能修改
像是

>for j := 2 to 10 do
>　var i : integer;
>　i := j;
>end do

**Comment by Naetw** [comment]
同學你好

> 這樣是不是 只有 arr 跟 arr2 是一樣的，然後 arr 跟 arr1 是不相同的？

對。

> 如果 arr[1]跟 arr1[3] 這樣也是一樣的嗎？

對，因為兩者 dimension 數量相同，且大小相同。

> 如果 func() 是redeclared的，是不是就不用檢查他的參數以及compound有沒有問題了？
同上，如果是func的參數redeclared，是不是也不用再檢查compound有沒有問題了？

要繼續檢查，要把所有能判斷的錯誤都找出來。

> 是合法的對吧(？

> In an array declaration, the index of the lower bound must be smaller than that of the upper bound. Both of the indices must be greater than or equal to zero; actually, a non-conforming input was already blocked according to the syntactic definition.

spec 中提到 smaller 沒有說 equal，所以不合法。

>  for的loop_var是可以被拿來引用的對吧？只是不能修改

對。這個在 #87 有問過囉。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by iamch15542** [comment]
助教您好，
其實我比較好奇的是
到底什麼時候會需要檢查array是不是same type
既然 arr 不能被assign，那不就幾乎不可能會遇到這種情況了嗎？

**Comment by Naetw** [comment]
函式的參數傳遞會需要。
