### ISSUE TITLE
Name conflict問題

### ISSUE THREAD

**Issue by yenjushan** [compiler-f19/Discussion#91]
SPEC中提到 : 
Name must be unique within a given scope. Within the inner scope, the identifier designates the entity declared in the inner scope; the entity declared in the outer scope is hidden within the inner scope.
但我不太確定，想請問，要是後宣告的 function 與 variable 名稱重複，請問可以將function加入symbol table 嗎。

**Comment by Naetw** [comment]
同學你好

> 但我不太確定，想請問，要是後宣告的 function 與 variable 名稱重複，請問可以將function加入symbol table 嗎。

不行。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by Darklanx** [comment]
```
self;
func(): boolean;
    begin
    end
end func


begin  
    var a: array 1 to 10 of array 10 to 100 of integer;
    var func: 100; // redeclaration???
    print a[func()][0];
end
end self
```
我想請問一下這種狀況是重複宣告嗎？
還是要把兩個func可以同時存在？
