### ISSUE TITLE
Function Call的Error

### ISSUE THREAD

**Issue by dd51108lai** [compiler-f19/Discussion#92]
> <Error> Found in line x, column y: incompatible types passing 'integer' to parameter of type 'boolean'
     func1(10);
           ^

這一個error發生時會檢查後續的argument嗎?
error的line和column要用argument的還是functioncall的?
若是有數個argument都有問題的話要output數個error嗎?

**Comment by Naetw** [comment]
同學你好

> 這一個error發生時會檢查後續的argument嗎?

要，因為彼此間不是 parent-child node 關係。

> error的line和column要用argument的還是functioncall的?

`^` 指向誰就是用誰，所以當然是 argument。

> 若是有數個argument都有問題的話要output數個error嗎?

當然要。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by dd51108lai** [comment]
那variable reference的
> <Error> Found in line x, column y: index of array reference must be an integer
     read a["SSLAB"];
也同理嗎

**Comment by Naetw** [comment]
Spec:

> Each index of an array reference must be of the integer type. Further checking regarding the array reference is unnecessary if an incorrect index was found within the array reference. The order of index checking is from left to right.

**Comment by Naetw** [comment]
現在才發現 `clang` 針對 function call 也會遇到錯誤就停 Orz，助教之後會去翻原始碼看看他們有沒有什麼考量，再對 spec 做修正，但這次就先依照目前的 spec 去實作，畢竟沒剩幾天。感謝同學提出疑問。
