### ISSUE TITLE
Loop_var數量

### ISSUE THREAD

**Issue by dd51108lai** [compiler-f19/Discussion#93]
助教您好
想問一下loop_var的問題
一個For固定只會有一個loop_var嗎?

若是assignment的assign array error 和incompatible error同時發生
incompatible error的error message是type和後續的array都要output嗎?
ex: <Error> Found in line x, column y: assigning to 'int [2]' from incompatible type 'string [3]'

**Comment by Naetw** [comment]
同學你好

> 一個For固定只會有一個loop_var嗎?

語法也只能放一個 ID 所以不會有多。

> incompatible error的error message是type和後續的array都要output嗎?

assign array error 就好，因為 array 不能 assign，再往下比較沒有意義。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
