### ISSUE TITLE
If/While Condition

### ISSUE THREAD

**Issue by dd51108lai** [compiler-f19/Discussion#94]
助教您好
> <Error> Found in line x, column y: the expression of condition must be boolean type
     if a + 10 then
          ^

這個error在condition是bool array的情況需要跳嗎

**Comment by Naetw** [comment]
> 這個error在condition是bool array的情況需要跳嗎

boolean array 不等於 boolean，要跳。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
