### ISSUE TITLE
position of '^' in expression in Variable reference

### ISSUE THREAD

**Issue by Darklanx** [compiler-f19/Discussion#95]
請問variable reference裡面的expression不是integer箭頭要指向哪
ex:
print a[1+1+1+1+0.2];

**Comment by Naetw** [comment]
同學你好

> 請問variable reference裡面的expression不是integer箭頭要指向哪

看你 expression node 紀錄什麼位置就指向那。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。
