### ISSUE TITLE
ReadStatement 以及同個節點內多個錯誤的檢查規則

### ISSUE THREAD

**Issue by dd51108lai** [compiler-f19/Discussion#96]
請問為什麼ReadStatement的第9行會對

> <Error> Found in line x, column y: variable reference of read statement cannot be a constant variable reference
     read c;
          ^

不會遇到這個error嗎

**Comment by YSHsieh7777** [comment]
> 請問為什麼ReadStatement的第9行會對

我看範例解答就是你講的那個 error 沒錯

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by dd51108lai** [comment]
那
><Error> Found in line 9, column 10: variable reference of read statement must be scalar type
        read constant;
             ^

這個呢?readnode是只要有一個錯接下來就不用檢查了嗎

**Comment by Naetw** [comment]
> 這個呢?readnode是只要有一個錯接下來就不用檢查了嗎

是，畢竟 read node 裡的三種錯誤不會有同時存在的狀況。

**Comment by dd51108lai** [comment]
那assignment的前兩個錯誤發生時呢
需要檢查後面兩個嗎
因為看assignment的第10行好像是不需要做後續檢查的

**Comment by Naetw** [comment]
基本上只有 program node 的頭尾兩個都要檢查之外，其他基本上照順序找錯誤，找到一個就可以馬上離開該節點了，同節點內的後續檢查都不用。
