### ISSUE TITLE
[Update][Dec 26, 2019, 23:09]  function variable name conflict.

### ISSUE THREAD

**Issue by Darklanx** [compiler-f19/Discussion#97]
```
self;
func(): boolean;
    begin
    end
end func


begin  
    var a: array 1 to 10 of array 10 to 100 of integer;
    var func: 100; // redeclaration???
    print a[func()][0];
end
end self
```
我想請問一下這種狀況是重複宣告嗎？
還是兩個func可以同時存在？

**Comment by Naetw** [comment]
> 我想請問一下這種狀況是重複宣告嗎？

是。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by Naetw** [comment]
@Darklanx 同學不好意思，助教看太快，以為是同名的 function 就直接回答了。正確的情況是變數 func 可以蓋掉函式 func，因為在不同 scope。若同學已經實作這樣的功能，可以不用修改，這次不會有這樣的測資。造成困擾不好意思。
