### ISSUE TITLE
error.p測資 / 是否要繼續檢查問題

### ISSUE THREAD

**Issue by phlee1117** [compiler-f19/Discussion#98]
助教您好
1. 這樣的 for迴圈裡面的 `a := 10` 算是合法的嗎？
```
begin
    var a:integer;
    for i := 10 to 12 do
          a := 10;
    end do
end
```

另外有5個是否要繼續檢查錯誤的問題

1. 當 function call 檢查到 param 數量缺少時，還需要繼續檢查 param type 正確嗎？
2. 當 function param 的 type 出錯時以及問題 1 的情況時，還需要回傳 function call 的 type 嗎？
ex ：print func(); 這時候還需要輸出像是`variable reference of print statement must be scalar type`的錯誤嗎？
還是已經不用管 print node 的 semantic check 了
3. error.p 的 line 31
a 在當前 scope 內是 undeclared 的，但沒有輸出error，是因為 loop var 出錯，所以for loop裡面就不用繼續檢查嗎？
4. 第二個 a 已經 redeclared 了，是不是要繼續檢查後面的array index
``` 
var a :integer;
var a := array 40 to 1 of boolean;
```
5. 當 func(a, b : integer) 是redeclared時，這時候還是需要印出func的symbol table對吧？包含他裡面param或是宣告的var

後面幾個都是 undeclared / redeclared 時是否要繼續檢查的問題，因為 spec 找不到相關說明
所以問題有點多，麻煩助教解答了，謝謝

**Comment by Naetw** [comment]
> 這樣的 for迴圈裡面的 a := 10 算是合法的嗎？

同學認為哪邊可能不合法？

> 當 function call 檢查到 param 數量缺少時，還需要繼續檢查 param type 正確嗎？

不用。

> 當 function param 的 type 出錯時以及問題 1 的情況時，還需要回傳 function call 的 type 嗎？

不用。另外函式回傳值其實沒有 array type。基本上原則就是某個 node 有錯誤被檢查到，後續跟它有關的就不用做（想像成因為有錯誤，所以 type 推論不出來）。

> a 在當前 scope 內是 undeclared 的，但沒有輸出error，是因為 loop var 出錯，所以for loop裡面就不用繼續檢查嗎？

a 有宣告啊，在 line 17。

> 第二個 a 已經 redeclared 了，是不是要繼續檢查後面的array index

Redeclared 就不會被放進 symbol table，也就檢查不到。若你是分開設計的話（參考 #80），助教想像得到的做法是遇到 declaration node 就直接把 redeclared symbol 清掉，也就不用再額外檢查其他問題了。

> 當 func(a, b : integer) 是redeclared時，這時候還是需要印出func的symbol table對吧？包含他裡面param或是宣告的var

這個問題牽涉到同樣是 #80 討論的議題，因為這次沒有確定要哪一種方式，所以基本上會有印出來跟沒印出來的版本。這邊若同學是分開設計的方式，在 report 稍微註記一下，我會特別看一下。

> 後面幾個都是 undeclared / redeclared 時是否要繼續檢查的問題，因為 spec 找不到相關說明

基本上只有 program node 的頭尾兩個都要檢查之外，其他基本上照順序找錯誤，找到一個就可以馬上離開該節點了，同節點內的後續檢查都不用。這邊是助教沒有說明清楚的地方，不好意思。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by phlee1117** [comment]
> 同學認為哪邊可能不合法？

所以`a:=10`中的 a 因為在begin end這個compound table的scope內，所以查的到合法，這個沒問題
```
begin
    var a:integer;
    for i := 10 to 12 do
          a := 10;
    end do
end
```
> a 有宣告啊，在 line 17。

但error.p測資中的31行的a，如下，他應該是在for loop裡面的那個compound table的scope中，應該看不到外面的另一個compound table中的變數才對吧？
```
begin
    var a : integer;

    for i := 1 to 10 do
    begin
        var i : integer;    // error redeclare
        for i := 2 to 3 do  // error same iterator
            a := 3;
        end do
    end
    end do
end
```
> Redeclared 就不會被放進 symbol table，也就檢查不到。

那如果是宣告funcion的時候redeclared了，還要繼續檢查該function內部結構（parameter，compound statement）嗎？
在 #90 中助教提到
>要繼續檢查，要把所有能判斷的錯誤都找出來。

好像跟這裡矛盾？

> 基本上只有 program node 的頭尾兩個都要檢查之外，其他基本上照順序找錯誤，找到一個就可以馬上離開該節點了，同節點內的後續檢查都不用。

1. 所以假設某function有2個參數，如果function call裡面的2個參數type都不符合，只需要印出最左邊那個錯就跳出了對嗎？
2. 同理，assignment的lval和expr都是array，只需要印出lval出錯就行了(左邊的child node先)？

3. If 和 While 的condition如果出錯，還要繼續去visit它的body嗎？感覺condition跟 If While 本身的semantic error無關，所以還是要繼續？

**Comment by Naetw** [comment]
> 但error.p測資中的31行的a，如下，他應該是在for loop裡面的那個compound table的scope中，應該看不到外面的另一個compound table中的變數才對吧？

Scope rule 跟 C 基本上一樣，而你內層範圍本來就看得到外面的變數，只要沒有重複宣告把它蓋掉的話。

> 好像跟這裡矛盾？

基本上之前的作業版本是把 symbol redeclaration 跟 semantic definition 分開，所以才會有這樣的決定。而且其實 function redeclaration 不在 error-msg 裡關於 function node 描述的錯誤之中，同時其他錯誤基本上是獨立的，像是變數宣告，或是函式主體內的其他節點，唯一可以說的應該就是 return node 不需要檢查。

> 所以假設某function有2個參數，如果function call裡面的2個參數type都不符合，只需要印出最左邊那個錯就跳出了對嗎？

這邊就跟 #92 有關，如果方便的話建議是全找，因為目前實作版本是這樣的，而且基本上是一個迴圈去跑，差在 log 完要不要直接離開而已，但的確跟 array reference 的檢查規範有點相衝突，這邊以目前的時間無法做更改，若同學要直接跳出也沒問題。之後若有相關錯誤而助教沒檢查到，有被扣分再來跟助教反應。

> 同理，assignment的lval和expr都是array，只需要印出lval出錯就行了(左邊的child node先)？

就照著 assignment node 所描述的錯誤依序檢查下來，有錯誤就跳出。

> If 和 While 的condition如果出錯，還要繼續去visit它的body嗎？感覺condition跟 If While 本身的semantic error無關，所以還是要繼續？

是的。

**Comment by iamch15542** [comment]
> 基本上只有 program node 的頭尾兩個都要檢查之外，其他基本上照順序找錯誤，找到一個就可以馬上離開該節點了，同節點內的後續檢查都不用。這邊是助教沒有說明清楚的地方，不好意思。

如果找到一個錯誤後，同節點內的後續檢查都不用，這樣是不是 loop_var 出錯也不用再繼續看下去了，可以直接跳離for 這個節點？

**Comment by Naetw** [comment]
「同節點內的後續檢查都不用」指的是「該節點」內所需要的檢查，像是 assignment node 有專屬它自己的檢查。若同學是指說 for node 裡面只要 loop_var 有問題，其他 statement node 就不用檢查，那這樣理解是錯誤的。
