### ISSUE TITLE
請問^要印在哪裡

### ISSUE THREAD

**Issue by samuelyutt** [compiler-f19/Discussion#99]
請問助教，如果是以下的錯誤輸出，請問`^`應該指向`(`還是指向`5`？
```
<Error> Found in line 20, column 16: return 'boolean' from a function with return type 'string'
        return (5 > 1.0 and false);
               ^
<Error> Found in line 13, column 14: index of array reference must be an integer
        b[1][(5>1.0 and true)] := 1;
              ^
```

**Comment by Naetw** [comment]
我們的 AST 沒有要求同學紀錄 `(` 的位置，它的作用只有影響優先順序而已。請使用 return value 節點以及 index expression 節點所紀錄的位置。

---

若以上回答有回答到同學的問題，請對助教的回覆加上 emoji 👍，助教會幫此 issue 加上「已解決」的標籤，感謝同學的配合。

**Comment by nax1016cs** [comment]
請問助教在上面的例子中，^ 要指在 5 還是true的t上，當5>1.0 and true這個expression parse結束的時候，應該會停留在true上，那這樣要往回指向5還是指向true才正確?

**Comment by Naetw** [comment]
都不正確。它是一個 expression，而實際上會是一個 binary operator，反正只要你 yacc rule 有符合作業三的規範，就直接輸出 binary operator 所紀錄的位置就好。
